// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";

export const auth: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"auth"
				]
			}
		},
		"default": "auth.whoami",
		"options": [
			{
				"name": "Whoami",
				"value": "auth.whoami",
				"action": "Whoami",
				"description": "Get the authenticated API account.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/whoami"
					}
				}
			},
			{
				"name": "Balance",
				"value": "billing.balance.get",
				"action": "Get account balance",
				"description": "Get your account credit balance.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/balance"
					}
				}
			}
		]
	}
];
