// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { cursorPagination } from "../shared/pagination";

export const facebook: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				]
			}
		},
		"default": "facebook.profile.get",
		"options": [
			{
				"name": "Profile",
				"value": "facebook.profile.get",
				"action": "Get Facebook profile",
				"description": "Get a Facebook profile or page.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/profiles"
					}
				}
			},
			{
				"name": "Profile posts",
				"value": "facebook.profile.posts.list",
				"action": "List Facebook profile posts",
				"description": "Get posts from a Facebook profile or page.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/profiles/posts"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Profile reels",
				"value": "facebook.profile.reels.list",
				"action": "List Facebook profile reels",
				"description": "Get Reels from a Facebook profile or page.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/profiles/reels"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Profile photos",
				"value": "facebook.profile.photos.list",
				"action": "List Facebook profile photos",
				"description": "Get photos from a Facebook profile or page.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/profiles/photos"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Post or reel",
				"value": "facebook.post.get",
				"action": "Get Facebook post or reel",
				"description": "Get a Facebook post or Reel.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/posts"
					}
				}
			},
			{
				"name": "Comments",
				"value": "facebook.post.comments.list",
				"action": "List Facebook post or reel comments",
				"description": "Get comments on a Facebook post or Reel.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/posts/comments"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Transcript",
				"value": "facebook.post.transcript.get",
				"action": "Get Facebook post transcript",
				"description": "Get the transcript for a Facebook post.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/posts/transcript"
					}
				}
			},
			{
				"name": "Group posts",
				"value": "facebook.group.posts.list",
				"action": "List Facebook group posts",
				"description": "Get posts from a Facebook group.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/groups/posts"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Marketplace item",
				"value": "facebook.marketplace.item.get",
				"action": "Get Facebook Marketplace item",
				"description": "Get details for a Facebook Marketplace listing.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/marketplace/items"
					}
				}
			},
			{
				"name": "Marketplace location search",
				"value": "facebook.marketplace.locations.search",
				"action": "Search Facebook Marketplace locations",
				"description": "Search Facebook Marketplace locations to obtain coordinates for listing search.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/marketplace/locations/search"
					}
				}
			},
			{
				"name": "Marketplace search",
				"value": "facebook.marketplace.search.list",
				"action": "Search Facebook Marketplace listings",
				"description": "Search Facebook Marketplace listings by keyword near a latitude and longitude.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/marketplace/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Ad library ad",
				"value": "facebook.adLibrary.ad.get",
				"action": "Get Facebook Ad Library ad",
				"description": "Get a single Facebook Ad Library ad by archive id or public Ad Library URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/ad-library/ads"
					}
				}
			},
			{
				"name": "Ad Library search",
				"value": "facebook.adLibrary.ads.search.get",
				"action": "Search Facebook Ad Library ads",
				"description": "Search Facebook Ad Library ads by keyword.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/ad-library/ads/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Company ads",
				"value": "facebook.company.ads.list",
				"action": "List Facebook company ads",
				"description": "List ads a company or page is running in the Facebook Ad Library.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/ad-library/companies/ads"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Ad library companies",
				"value": "facebook.adLibrary.companies.search",
				"action": "Search Facebook ad library companies",
				"description": "Search Facebook ad library companies by name.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/facebook/ad-library/companies/search"
					}
				}
			}
		]
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Facebook public profile or page URL to look up.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.profile.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.profile.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Include Business Hours",
				"name": "includeBusinessHours",
				"type": "boolean",
				"default": false,
				"description": "Optional: include structured business hours in the response when available.",
				"routing": {
					"send": {
						"type": "query",
						"property": "includeBusinessHours"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.profile.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.profile.posts.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Url",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Full public Facebook profile or page URL.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			},
			{
				"displayName": "Page Id",
				"name": "pageId",
				"type": "string",
				"default": "",
				"description": "Facebook page or profile id when you have it instead of a full URL.",
				"routing": {
					"send": {
						"type": "query",
						"property": "pageId"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.profile.reels.list"
				]
			}
		}
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public Facebook profile or page URL whose reels should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.profile.reels.list"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.profile.photos.list"
				]
			}
		}
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public Facebook profile or page URL whose photos should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.profile.photos.list"
				]
			}
		}
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public permalink to the Facebook post or reel.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.post.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.post.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Include Comments",
				"name": "includeComments",
				"type": "boolean",
				"default": false,
				"description": "When true, includes a sample of top-level comments when available.",
				"routing": {
					"send": {
						"type": "query",
						"property": "includeComments"
					}
				}
			},
			{
				"displayName": "Include Transcript",
				"name": "includeTranscript",
				"type": "boolean",
				"default": false,
				"description": "When true, includes a plain-text transcript when available for the video.",
				"routing": {
					"send": {
						"type": "query",
						"property": "includeTranscript"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.post.comments.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.post.comments.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Url",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Link to the Facebook post or reel whose comments should be listed.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			},
			{
				"displayName": "Feedback Id",
				"name": "feedbackId",
				"type": "string",
				"default": "",
				"description": "Optional Facebook feedback identifier for the target post; when available it can improve lookup performance.",
				"routing": {
					"send": {
						"type": "query",
						"property": "feedbackId"
					}
				}
			}
		]
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the Facebook post or reel whose transcript should be returned.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.post.transcript.get"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.group.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public Facebook group URL whose posts should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.group.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.group.posts.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Sort By",
				"name": "sortBy",
				"type": "options",
				"options": [
					{
						"name": "Top",
						"value": "top"
					},
					{
						"name": "Recent Activity",
						"value": "recentActivity"
					},
					{
						"name": "Chronological",
						"value": "chronological"
					},
					{
						"name": "Chronological Listings",
						"value": "chronologicalListings"
					}
				],
				"default": "top",
				"description": "Optional sort order for the returned posts.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sortBy"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.marketplace.item.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Item Id",
				"name": "itemId",
				"type": "string",
				"default": "",
				"description": "Facebook Marketplace item identifier. Provide this instead of url when you already know the item id.",
				"routing": {
					"send": {
						"type": "query",
						"property": "itemId"
					}
				}
			},
			{
				"displayName": "Url",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Public Facebook Marketplace item URL.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			}
		]
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "City or place name to search for Facebook Marketplace locations.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.marketplace.locations.search"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.marketplace.search.list"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for marketplace listings.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.marketplace.search.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.marketplace.search.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Lat",
				"name": "lat",
				"type": "number",
				"default": 0,
				"description": "Latitude for the marketplace search location.",
				"routing": {
					"send": {
						"type": "query",
						"property": "lat"
					}
				}
			},
			{
				"displayName": "Lng",
				"name": "lng",
				"type": "number",
				"default": 0,
				"description": "Longitude for the marketplace search location.",
				"routing": {
					"send": {
						"type": "query",
						"property": "lng"
					}
				}
			},
			{
				"displayName": "Radius Km",
				"name": "radiusKm",
				"type": "number",
				"default": 0,
				"description": "Optional search radius in kilometers.",
				"routing": {
					"send": {
						"type": "query",
						"property": "radiusKm"
					}
				}
			},
			{
				"displayName": "Min Price",
				"name": "minPrice",
				"type": "number",
				"default": 0,
				"description": "Optional minimum listing price.",
				"routing": {
					"send": {
						"type": "query",
						"property": "minPrice"
					}
				}
			},
			{
				"displayName": "Max Price",
				"name": "maxPrice",
				"type": "number",
				"default": 0,
				"description": "Optional maximum listing price.",
				"routing": {
					"send": {
						"type": "query",
						"property": "maxPrice"
					}
				}
			},
			{
				"displayName": "Count",
				"name": "count",
				"type": "number",
				"default": 0,
				"description": "Optional number of listings to return.",
				"routing": {
					"send": {
						"type": "query",
						"property": "count"
					}
				}
			},
			{
				"displayName": "Sort By",
				"name": "sortBy",
				"type": "options",
				"options": [
					{
						"name": "Suggested",
						"value": "suggested"
					},
					{
						"name": "Distance Ascend",
						"value": "distanceAscend"
					},
					{
						"name": "Creation Time Descend",
						"value": "creationTimeDescend"
					},
					{
						"name": "Price Ascend",
						"value": "priceAscend"
					},
					{
						"name": "Price Descend",
						"value": "priceDescend"
					}
				],
				"default": "suggested",
				"description": "Optional sort order for marketplace listings.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sortBy"
					}
				}
			},
			{
				"displayName": "Delivery Method",
				"name": "deliveryMethod",
				"type": "options",
				"options": [
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Local Pickup",
						"value": "localPickup"
					},
					{
						"name": "Shipping",
						"value": "shipping"
					}
				],
				"default": "all",
				"description": "Optional delivery method filter for marketplace listings.",
				"routing": {
					"send": {
						"type": "query",
						"property": "deliveryMethod"
					}
				}
			},
			{
				"displayName": "Condition",
				"name": "condition",
				"type": "options",
				"options": [
					{
						"name": "New",
						"value": "new"
					},
					{
						"name": "Used Like New",
						"value": "usedLikeNew"
					},
					{
						"name": "Used Good",
						"value": "usedGood"
					},
					{
						"name": "Used Fair",
						"value": "usedFair"
					}
				],
				"default": "new",
				"description": "Optional item condition filter for marketplace listings.",
				"routing": {
					"send": {
						"type": "query",
						"property": "condition"
					}
				}
			},
			{
				"displayName": "Date Listed",
				"name": "dateListed",
				"type": "options",
				"options": [
					{
						"name": "1",
						"value": "1"
					},
					{
						"name": "7",
						"value": "7"
					},
					{
						"name": "30",
						"value": "30"
					},
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Last24 Hours",
						"value": "last24Hours"
					},
					{
						"name": "Last7 Days",
						"value": "last7Days"
					},
					{
						"name": "Last30 Days",
						"value": "last30Days"
					}
				],
				"default": "1",
				"description": "Optional date-listed filter for marketplace listings.",
				"routing": {
					"send": {
						"type": "query",
						"property": "dateListed"
					}
				}
			},
			{
				"displayName": "Availability",
				"name": "availability",
				"type": "options",
				"options": [
					{
						"name": "Available",
						"value": "available"
					},
					{
						"name": "Sold",
						"value": "sold"
					},
					{
						"name": "All",
						"value": "all"
					}
				],
				"default": "available",
				"description": "Optional availability filter for marketplace listings.",
				"routing": {
					"send": {
						"type": "query",
						"property": "availability"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.adLibrary.ad.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Ad Id",
				"name": "adId",
				"type": "string",
				"default": "",
				"description": "Facebook Ad Library archive id for the ad.",
				"routing": {
					"send": {
						"type": "query",
						"property": "adId"
					}
				}
			},
			{
				"displayName": "Url",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Public Facebook Ad Library URL for the ad.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			},
			{
				"displayName": "Include Transcript",
				"name": "includeTranscript",
				"type": "boolean",
				"default": false,
				"description": "When true, includes a plain-text transcript when available for the ad video.",
				"routing": {
					"send": {
						"type": "query",
						"property": "includeTranscript"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, requests a smaller upstream payload before normalization.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.adLibrary.ads.search.get"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for Facebook Ad Library ads.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.adLibrary.ads.search.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.adLibrary.ads.search.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Sort By",
				"name": "sortBy",
				"type": "options",
				"options": [
					{
						"name": "Impressions",
						"value": "impressions"
					},
					{
						"name": "Most Recent",
						"value": "most-recent"
					}
				],
				"default": "impressions",
				"description": "Optional sort order for returned ads.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sortBy"
					}
				}
			},
			{
				"displayName": "Search Type",
				"name": "searchType",
				"type": "options",
				"options": [
					{
						"name": "Keyword Unordered",
						"value": "keyword-unordered"
					},
					{
						"name": "Exact Phrase",
						"value": "exact-phrase"
					}
				],
				"default": "keyword-unordered",
				"description": "Optional keyword matching mode for the search query.",
				"routing": {
					"send": {
						"type": "query",
						"property": "searchType"
					}
				}
			},
			{
				"displayName": "Ad Type",
				"name": "adType",
				"type": "options",
				"options": [
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Political And Issue",
						"value": "political-and-issue"
					}
				],
				"default": "all",
				"description": "Optional filter for all ads or political and issue ads.",
				"routing": {
					"send": {
						"type": "query",
						"property": "adType"
					}
				}
			},
			{
				"displayName": "Country",
				"name": "country",
				"type": "string",
				"default": "",
				"description": "Optional country code filter. Use ALL to search all countries.",
				"routing": {
					"send": {
						"type": "query",
						"property": "country"
					}
				}
			},
			{
				"displayName": "Status",
				"name": "status",
				"type": "options",
				"options": [
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Active",
						"value": "active"
					},
					{
						"name": "Inactive",
						"value": "inactive"
					}
				],
				"default": "all",
				"description": "Optional ad status filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "status"
					}
				}
			},
			{
				"displayName": "Media Type",
				"name": "mediaType",
				"type": "options",
				"options": [
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Image",
						"value": "image"
					},
					{
						"name": "Video",
						"value": "video"
					},
					{
						"name": "Meme",
						"value": "meme"
					},
					{
						"name": "Image And Meme",
						"value": "image-and-meme"
					},
					{
						"name": "None",
						"value": "none"
					}
				],
				"default": "all",
				"description": "Optional creative media filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "mediaType"
					}
				}
			},
			{
				"displayName": "Start Date",
				"name": "startDate",
				"type": "string",
				"default": "",
				"description": "Optional start date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "startDate"
					}
				}
			},
			{
				"displayName": "End Date",
				"name": "endDate",
				"type": "string",
				"default": "",
				"description": "Optional end date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "endDate"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, returns a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.company.ads.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.company.ads.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Page Id",
				"name": "pageId",
				"type": "string",
				"default": "",
				"description": "Facebook page id when you have it instead of a company name.",
				"routing": {
					"send": {
						"type": "query",
						"property": "pageId"
					}
				}
			},
			{
				"displayName": "Company Name",
				"name": "companyName",
				"type": "string",
				"default": "",
				"description": "Company or page name to search when you do not have a page id.",
				"routing": {
					"send": {
						"type": "query",
						"property": "companyName"
					}
				}
			},
			{
				"displayName": "Country",
				"name": "country",
				"type": "string",
				"default": "",
				"description": "Optional country code filter. Use ALL to search all countries.",
				"routing": {
					"send": {
						"type": "query",
						"property": "country"
					}
				}
			},
			{
				"displayName": "Status",
				"name": "status",
				"type": "options",
				"options": [
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Active",
						"value": "active"
					},
					{
						"name": "Inactive",
						"value": "inactive"
					}
				],
				"default": "all",
				"description": "Optional ad status filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "status"
					}
				}
			},
			{
				"displayName": "Media Type",
				"name": "mediaType",
				"type": "options",
				"options": [
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Image",
						"value": "image"
					},
					{
						"name": "Video",
						"value": "video"
					},
					{
						"name": "Meme",
						"value": "meme"
					},
					{
						"name": "Image And Meme",
						"value": "image-and-meme"
					},
					{
						"name": "None",
						"value": "none"
					}
				],
				"default": "all",
				"description": "Optional creative media filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "mediaType"
					}
				}
			},
			{
				"displayName": "Language",
				"name": "language",
				"type": "string",
				"default": "",
				"description": "Optional language code filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "language"
					}
				}
			},
			{
				"displayName": "Sort By",
				"name": "sortBy",
				"type": "options",
				"options": [
					{
						"name": "Impressions",
						"value": "impressions"
					},
					{
						"name": "Most Recent",
						"value": "most-recent"
					}
				],
				"default": "impressions",
				"description": "Optional sort order for returned ads.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sortBy"
					}
				}
			},
			{
				"displayName": "Start Date",
				"name": "startDate",
				"type": "string",
				"default": "",
				"description": "Optional start date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "startDate"
					}
				}
			},
			{
				"displayName": "End Date",
				"name": "endDate",
				"type": "string",
				"default": "",
				"description": "Optional end date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "endDate"
					}
				}
			}
		]
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for Facebook ad library companies.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"facebook"
				],
				"operation": [
					"facebook.adLibrary.companies.search"
				]
			}
		}
	}
];
