// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { cursorPagination } from "../shared/pagination";

export const google: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"google"
				]
			}
		},
		"default": "google.company.ads.list",
		"options": [
			{
				"name": "Company Ads",
				"value": "google.company.ads.list",
				"action": "List Google company ads",
				"description": "List ads a company or advertiser is running in Google Ad Transparency.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/google/ad-library/companies/ads"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Ad Library Ad",
				"value": "google.adLibrary.ad.get",
				"action": "Get Google Ad Library ad",
				"description": "Get a single Google Ad Transparency creative by public Ad Transparency URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/google/ad-library/ads"
					}
				}
			},
			{
				"name": "Ad Library Advertisers",
				"value": "google.adLibrary.advertisers.search",
				"action": "Search Google Ad Library advertisers",
				"description": "Search Google Ad Transparency advertisers by name.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/google/ad-library/advertisers/search"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"google"
				],
				"operation": [
					"google.company.ads.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"google"
				],
				"operation": [
					"google.company.ads.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Domain",
				"name": "domain",
				"type": "string",
				"default": "",
				"description": "Company domain when you do not have an advertiser id.",
				"routing": {
					"send": {
						"type": "query",
						"property": "domain"
					}
				}
			},
			{
				"displayName": "Advertiser ID",
				"name": "advertiserId",
				"type": "string",
				"default": "",
				"description": "Google Ad Transparency advertiser id when you have it instead of a domain.",
				"routing": {
					"send": {
						"type": "query",
						"property": "advertiserId"
					}
				}
			},
			{
				"displayName": "Topic",
				"name": "topic",
				"type": "options",
				"options": [
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Political",
						"value": "political"
					}
				],
				"default": "all",
				"description": "Optional topic filter. When `political`, `region` is required.",
				"routing": {
					"send": {
						"type": "query",
						"property": "topic"
					}
				}
			},
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional region filter as a two-letter country code.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Start Date",
				"name": "startDate",
				"type": "string",
				"default": "",
				"description": "Optional start date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "startDate"
					}
				}
			},
			{
				"displayName": "End Date",
				"name": "endDate",
				"type": "string",
				"default": "",
				"description": "Optional end date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "endDate"
					}
				}
			},
			{
				"displayName": "Platform",
				"name": "platform",
				"type": "options",
				"options": [
					{
						"name": "Google Maps",
						"value": "google_maps"
					},
					{
						"name": "Google Play",
						"value": "google_play"
					},
					{
						"name": "Google Search",
						"value": "google_search"
					},
					{
						"name": "Google Shopping",
						"value": "google_shopping"
					},
					{
						"name": "Youtube",
						"value": "youtube"
					}
				],
				"default": "google_maps",
				"description": "Optional Google surface filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "platform"
					}
				}
			},
			{
				"displayName": "Format",
				"name": "format",
				"type": "options",
				"options": [
					{
						"name": "Text",
						"value": "text"
					},
					{
						"name": "Image",
						"value": "image"
					},
					{
						"name": "Video",
						"value": "video"
					}
				],
				"default": "text",
				"description": "Optional creative format filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "format"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public Google Ad Transparency URL for the creative.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"google"
				],
				"operation": [
					"google.adLibrary.ad.get"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for Google Ad Transparency advertisers.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"google"
				],
				"operation": [
					"google.adLibrary.advertisers.search"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"google"
				],
				"operation": [
					"google.adLibrary.advertisers.search"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Two-letter country code to search in. Default: `US`.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			}
		]
	}
];
