// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { cursorPagination } from "../shared/pagination";

export const hackernews: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				]
			}
		},
		"default": "hackernews.search.list",
		"options": [
			{
				"name": "Search",
				"value": "hackernews.search.list",
				"action": "Search Hacker News",
				"description": "Search Hacker News by keyword.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/hackernews/search"
					}
				}
			},
			{
				"name": "Feed",
				"value": "hackernews.feed.list",
				"action": "List a Hacker News feed",
				"description": "List a Hacker News feed by type (top, new, best, ask, show, or jobs).",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/hackernews/feeds/{{$parameter[\"feed\"]}}"
					}
				}
			},
			{
				"name": "Story",
				"value": "hackernews.story.get",
				"action": "Get Hacker News story",
				"description": "Get a Hacker News story by id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/hackernews/stories/{{$parameter[\"id\"]}}"
					}
				}
			},
			{
				"name": "Story Comments",
				"value": "hackernews.story.comments.list",
				"action": "Get Hacker News story comments",
				"description": "List comments on a Hacker News story by id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/hackernews/stories/{{$parameter[\"id\"]}}/comments"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Item",
				"value": "hackernews.item.get",
				"action": "Get Hacker News item",
				"description": "Get a Hacker News item by id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/hackernews/items/{{$parameter[\"id\"]}}"
					}
				}
			},
			{
				"name": "Comment Context",
				"value": "hackernews.comment.context.get",
				"action": "Get Hacker News comment context",
				"description": "Get a Hacker News comment with its ancestor chain to the root story.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/hackernews/comments/{{$parameter[\"id\"]}}/context"
					}
				}
			},
			{
				"name": "User",
				"value": "hackernews.user.get",
				"action": "Get Hacker News user profile",
				"description": "Get a Hacker News user profile by username.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/hackernews/users/{{$parameter[\"username\"]}}"
					}
				}
			},
			{
				"name": "User Submissions",
				"value": "hackernews.user.submissions.list",
				"action": "List Hacker News user submissions",
				"description": "List a Hacker News user's stories, polls, and jobs (newest first).",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/hackernews/users/{{$parameter[\"username\"]}}/submissions"
					}
				}
			},
			{
				"name": "User Comments",
				"value": "hackernews.user.comments.list",
				"action": "List Hacker News user comments",
				"description": "List a Hacker News user's comments (newest first).",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/hackernews/users/{{$parameter[\"username\"]}}/comments"
					}
				}
			},
			{
				"name": "User Favorites",
				"value": "hackernews.user.favorites.list",
				"action": "List Hacker News user favorites",
				"description": "List favorites for a Hacker News user by username.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/hackernews/users/{{$parameter[\"username\"]}}/favorites"
					}
				}
			},
			{
				"name": "Who Is Hiring",
				"value": "hackernews.jobs.who_is_hiring.list",
				"action": "List Who is Hiring jobs",
				"description": "List top-level jobs from the monthly Hacker News Who is Hiring thread (latest thread, or a YYYY-MM month).",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/hackernews/jobs/who-is-hiring"
					}
				}
			},
			{
				"name": "Updates",
				"value": "hackernews.updates.get",
				"action": "Get Hacker News updates",
				"description": "Get recently changed Hacker News item ids and usernames.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/hackernews/updates"
					}
				}
			},
			{
				"name": "Max Item",
				"value": "hackernews.maxitem.get",
				"action": "Get Hacker News max item id",
				"description": "Get the current largest Hacker News item id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/hackernews/maxitem"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.search.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Query",
				"name": "query",
				"type": "string",
				"default": "",
				"description": "Full-text search query. Required unless `frontPageOnly`, `author`, `domain`, or `url` is set.",
				"placeholder": "e.g. automation",
				"routing": {
					"send": {
						"type": "query",
						"property": "query"
					}
				}
			},
			{
				"displayName": "Type",
				"name": "type",
				"type": "options",
				"options": [
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Story",
						"value": "story"
					},
					{
						"name": "Comment",
						"value": "comment"
					},
					{
						"name": "Ask Hn",
						"value": "ask_hn"
					},
					{
						"name": "Show Hn",
						"value": "show_hn"
					},
					{
						"name": "Launch Hn",
						"value": "launch_hn"
					},
					{
						"name": "Job",
						"value": "job"
					},
					{
						"name": "Poll",
						"value": "poll"
					}
				],
				"default": "all",
				"description": "Content type filter. Default: `all`.",
				"routing": {
					"send": {
						"type": "query",
						"property": "type"
					}
				}
			},
			{
				"displayName": "Sort",
				"name": "sort",
				"type": "options",
				"options": [
					{
						"name": "Popularity",
						"value": "popularity"
					},
					{
						"name": "Date",
						"value": "date"
					}
				],
				"default": "popularity",
				"description": "Ranking mode. Default: `popularity`.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sort"
					}
				}
			},
			{
				"displayName": "Date Range",
				"name": "dateRange",
				"type": "options",
				"options": [
					{
						"name": "24h",
						"value": "24h"
					},
					{
						"name": "Week",
						"value": "week"
					},
					{
						"name": "Month",
						"value": "month"
					},
					{
						"name": "Year",
						"value": "year"
					},
					{
						"name": "All",
						"value": "all"
					}
				],
				"default": "24h",
				"description": "Creation-time window. Default: `all`.",
				"routing": {
					"send": {
						"type": "query",
						"property": "dateRange"
					}
				}
			},
			{
				"displayName": "Page",
				"name": "page",
				"type": "number",
				"default": 0,
				"description": "Zero-based page index (maximum 50 pages, up to 1,000 hits).",
				"routing": {
					"send": {
						"type": "query",
						"property": "page"
					}
				}
			},
			{
				"displayName": "Page Size",
				"name": "pageSize",
				"type": "number",
				"default": 20,
				"description": "Hits per page. Default: 20.",
				"routing": {
					"send": {
						"type": "query",
						"property": "pageSize"
					}
				}
			},
			{
				"displayName": "Front Page Only",
				"name": "frontPageOnly",
				"type": "boolean",
				"default": false,
				"description": "When true, restrict results to current front-page items. Allows omitting `query`.",
				"routing": {
					"send": {
						"type": "query",
						"property": "frontPageOnly"
					}
				}
			},
			{
				"displayName": "Search Story Text",
				"name": "searchStoryText",
				"type": "boolean",
				"default": false,
				"description": "Include story/comment text in searchable fields. Default: true. Set false to search title/URL only.",
				"routing": {
					"send": {
						"type": "query",
						"property": "searchStoryText"
					}
				}
			},
			{
				"displayName": "Search Author",
				"name": "searchAuthor",
				"type": "boolean",
				"default": false,
				"description": "When true, include author username in the searchable fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "searchAuthor"
					}
				}
			},
			{
				"displayName": "Prefix",
				"name": "prefix",
				"type": "boolean",
				"default": false,
				"description": "When true, enable prefix matching for query tokens.",
				"routing": {
					"send": {
						"type": "query",
						"property": "prefix"
					}
				}
			},
			{
				"displayName": "Typo Tolerance",
				"name": "typoTolerance",
				"type": "boolean",
				"default": false,
				"description": "Enable typo tolerance. Default: true.",
				"routing": {
					"send": {
						"type": "query",
						"property": "typoTolerance"
					}
				}
			},
			{
				"displayName": "Author",
				"name": "author",
				"type": "string",
				"default": "",
				"description": "Restrict results to items by this Hacker News username.",
				"routing": {
					"send": {
						"type": "query",
						"property": "author"
					}
				}
			},
			{
				"displayName": "Domain",
				"name": "domain",
				"type": "string",
				"default": "",
				"description": "Restrict search to story URLs matching this domain (e.g. example.com). Can omit `query`.",
				"routing": {
					"send": {
						"type": "query",
						"property": "domain"
					}
				}
			},
			{
				"displayName": "URL",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Restrict search to story URLs matching this URL substring. Can omit `query`.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			},
			{
				"displayName": "Min Points",
				"name": "minPoints",
				"type": "number",
				"default": 0,
				"description": "Minimum points/score filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "minPoints"
					}
				}
			}
		]
	},
	{
		"displayName": "Feed",
		"name": "feed",
		"type": "options",
		"options": [
			{
				"name": "Top",
				"value": "top"
			},
			{
				"name": "New",
				"value": "new"
			},
			{
				"name": "Best",
				"value": "best"
			},
			{
				"name": "Ask",
				"value": "ask"
			},
			{
				"name": "Show",
				"value": "show"
			},
			{
				"name": "Jobs",
				"value": "jobs"
			}
		],
		"default": "top",
		"description": "Hacker News feed: top, new, best, ask, show, or jobs.",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.feed.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.feed.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Limit",
				"name": "limit",
				"type": "number",
				"default": 30,
				"description": "Maximum items to hydrate (1–50). Default: 30.",
				"routing": {
					"send": {
						"type": "query",
						"property": "limit"
					}
				}
			},
			{
				"displayName": "Offset",
				"name": "offset",
				"type": "number",
				"default": 0,
				"description": "Zero-based offset into the official feed id list.",
				"routing": {
					"send": {
						"type": "query",
						"property": "offset"
					}
				}
			}
		]
	},
	{
		"displayName": "ID",
		"name": "id",
		"type": "number",
		"default": 0,
		"description": "Hacker News story id.",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.story.get"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.story.comments.list"
				]
			}
		}
	},
	{
		"displayName": "ID",
		"name": "id",
		"type": "number",
		"default": 0,
		"description": "Hacker News story id whose comment tree should be returned.",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.story.comments.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.story.comments.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Limit",
				"name": "limit",
				"type": "number",
				"default": 50,
				"description": "Maximum comment nodes to return in this page (1–100). Default: 50.",
				"routing": {
					"send": {
						"type": "query",
						"property": "limit"
					}
				}
			}
		]
	},
	{
		"displayName": "ID",
		"name": "id",
		"type": "number",
		"default": 0,
		"description": "Hacker News item id.",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.item.get"
				]
			}
		}
	},
	{
		"displayName": "ID",
		"name": "id",
		"type": "number",
		"default": 0,
		"description": "Hacker News comment id.",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.comment.context.get"
				]
			}
		}
	},
	{
		"displayName": "Username",
		"name": "username",
		"type": "string",
		"default": "",
		"description": "Hacker News username (case-sensitive).",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.user.get"
				]
			}
		}
	},
	{
		"displayName": "Username",
		"name": "username",
		"type": "string",
		"default": "",
		"description": "Hacker News username (case-sensitive).",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.user.submissions.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.user.submissions.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Page",
				"name": "page",
				"type": "number",
				"default": 0,
				"description": "Zero-based page index (maximum 50 pages, up to 1,000 hits).",
				"routing": {
					"send": {
						"type": "query",
						"property": "page"
					}
				}
			},
			{
				"displayName": "Page Size",
				"name": "pageSize",
				"type": "number",
				"default": 20,
				"description": "Hits per page (1–50). Default: 20.",
				"routing": {
					"send": {
						"type": "query",
						"property": "pageSize"
					}
				}
			}
		]
	},
	{
		"displayName": "Username",
		"name": "username",
		"type": "string",
		"default": "",
		"description": "Hacker News username (case-sensitive).",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.user.comments.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.user.comments.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Page",
				"name": "page",
				"type": "number",
				"default": 0,
				"description": "Zero-based page index (maximum 50 pages, up to 1,000 hits).",
				"routing": {
					"send": {
						"type": "query",
						"property": "page"
					}
				}
			},
			{
				"displayName": "Page Size",
				"name": "pageSize",
				"type": "number",
				"default": 20,
				"description": "Hits per page (1–50). Default: 20.",
				"routing": {
					"send": {
						"type": "query",
						"property": "pageSize"
					}
				}
			}
		]
	},
	{
		"displayName": "Username",
		"name": "username",
		"type": "string",
		"default": "",
		"description": "Hacker News username (case-sensitive).",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.user.favorites.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.user.favorites.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Page",
				"name": "page",
				"type": "number",
				"default": 1,
				"description": "One-based HTML favorites page number. Default: 1. Each page bills 1 credit.",
				"routing": {
					"send": {
						"type": "query",
						"property": "page"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"hackernews"
				],
				"operation": [
					"hackernews.jobs.who_is_hiring.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Month",
				"name": "month",
				"type": "string",
				"default": "",
				"description": "Calendar month (YYYY-MM) to pin a Who is Hiring thread. Default: latest thread.",
				"routing": {
					"send": {
						"type": "query",
						"property": "month"
					}
				}
			},
			{
				"displayName": "Page",
				"name": "page",
				"type": "number",
				"default": 0,
				"description": "Zero-based page index of top-level hiring comments.",
				"routing": {
					"send": {
						"type": "query",
						"property": "page"
					}
				}
			},
			{
				"displayName": "Page Size",
				"name": "pageSize",
				"type": "number",
				"default": 20,
				"description": "Job rows per page (1–50). Default: 20.",
				"routing": {
					"send": {
						"type": "query",
						"property": "pageSize"
					}
				}
			}
		]
	}
];
