// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { tiktok } from "./tiktok.generated";
import { twitter } from "./twitter.generated";
import { telegram } from "./telegram.generated";
import { facebook } from "./facebook.generated";
import { google } from "./google.generated";
import { instagram } from "./instagram.generated";
import { threads } from "./threads.generated";
import { linkedin } from "./linkedin.generated";
import { reddit } from "./reddit.generated";
import { spotify } from "./spotify.generated";
import { youtube } from "./youtube.generated";
import { web } from "./web.generated";
import { auth } from "./auth.generated";

export const resourceOptions = [
	{
		"name": "TikTok",
		"value": "tiktok"
	},
	{
		"name": "Twitter",
		"value": "twitter"
	},
	{
		"name": "Telegram",
		"value": "telegram"
	},
	{
		"name": "Facebook",
		"value": "facebook"
	},
	{
		"name": "Google",
		"value": "google"
	},
	{
		"name": "Instagram",
		"value": "instagram"
	},
	{
		"name": "Threads",
		"value": "threads"
	},
	{
		"name": "LinkedIn",
		"value": "linkedin"
	},
	{
		"name": "Reddit",
		"value": "reddit"
	},
	{
		"name": "Spotify",
		"value": "spotify"
	},
	{
		"name": "YouTube",
		"value": "youtube"
	},
	{
		"name": "Web",
		"value": "web"
	},
	{
		"name": "Account",
		"value": "auth"
	}
];

export const allResourceProperties: INodeProperties[] = [
	...tiktok,
	...twitter,
	...telegram,
	...facebook,
	...google,
	...instagram,
	...threads,
	...linkedin,
	...reddit,
	...spotify,
	...youtube,
	...web,
	...auth,
];
