// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { cursorPagination } from "../shared/pagination";

export const instagram: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				]
			}
		},
		"default": "instagram.profile.get",
		"options": [
			{
				"name": "Profile",
				"value": "instagram.profile.get",
				"action": "Get Instagram profile",
				"description": "Get a full Instagram profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/instagram/profiles/{{$parameter[\"handle\"]}}"
					}
				}
			},
			{
				"name": "Basic profile",
				"value": "instagram.profile.basic.get",
				"action": "Get Instagram basic profile",
				"description": "Get a lightweight Instagram profile by numeric user ID.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/instagram/profiles/{{$parameter[\"userId\"]}}/basic"
					}
				}
			},
			{
				"name": "Profile posts",
				"value": "instagram.profile.posts.list",
				"action": "List Instagram profile posts",
				"description": "Get posts from a specific Instagram profile.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/instagram/profiles/{{$parameter[\"handle\"]}}/posts"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Profile reels",
				"value": "instagram.profile.reels.list",
				"action": "List Instagram profile reels",
				"description": "Get Reels from a specific Instagram profile.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/instagram/profiles/{{$parameter[\"handle\"]}}/reels"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Profile highlights",
				"value": "instagram.profile.highlights.list",
				"action": "List Instagram profile highlights",
				"description": "List story highlight albums for an Instagram profile.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/instagram/profiles/{{$parameter[\"handle\"]}}/highlights"
					}
				}
			},
			{
				"name": "Highlight",
				"value": "instagram.highlight.get",
				"action": "Get Instagram highlight",
				"description": "Get stories from a saved Instagram highlight.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/instagram/highlights/{{$parameter[\"highlightId\"]}}"
					}
				}
			},
			{
				"name": "Post or reel",
				"value": "instagram.post.get",
				"action": "Get Instagram post or reel",
				"description": "Get a single Instagram post or Reel.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/instagram/posts"
					}
				}
			},
			{
				"name": "Comments",
				"value": "instagram.post.comments.list",
				"action": "List Instagram post or reel comments",
				"description": "Get comments on an Instagram post or Reel.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/instagram/posts/comments"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Transcript",
				"value": "instagram.post.transcript.get",
				"action": "Get Instagram post transcript",
				"description": "Get the transcript for an Instagram post or Reel.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/instagram/posts/transcript"
					}
				}
			},
			{
				"name": "Search reels",
				"value": "instagram.search.reels.list",
				"action": "Search Instagram Reels",
				"description": "Search Instagram Reels by keyword with optional date filters and page-based pagination.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/instagram/search/reels"
					}
				}
			}
		]
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "Instagram handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.profile.get"
				]
			}
		}
	},
	{
		"displayName": "User Id",
		"name": "userId",
		"type": "string",
		"default": "",
		"description": "Instagram numeric user id to look up.",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.profile.basic.get"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.profile.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "Instagram handle whose posts should be listed.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.profile.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.profile.reels.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "Instagram handle whose reels should be listed.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.profile.reels.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "Instagram handle whose story highlight albums should be listed.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.profile.highlights.list"
				]
			}
		}
	},
	{
		"displayName": "Highlight Id",
		"name": "highlightId",
		"type": "string",
		"default": "",
		"description": "Numeric Instagram highlight id from a highlight URL.",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.highlight.get"
				]
			}
		}
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the post or reel.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.post.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.post.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional two-letter region (country code) for request routing.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, returns a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			},
			{
				"displayName": "Download Media",
				"name": "downloadMedia",
				"type": "boolean",
				"default": false,
				"description": "When true, returns permanent CDN URLs for media in `downloads`. Adds 10 credits (11 total including the base lookup).",
				"routing": {
					"send": {
						"type": "query",
						"property": "downloadMedia"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.post.comments.list"
				]
			}
		}
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the Instagram post or reel whose comments should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.post.comments.list"
				]
			}
		}
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the Instagram post or Reel whose transcript should be returned.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.post.transcript.get"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for Instagram Reels.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.search.reels.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"instagram"
				],
				"operation": [
					"instagram.search.reels.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Date Posted",
				"name": "datePosted",
				"type": "options",
				"options": [
					{
						"name": "Last Hour",
						"value": "last-hour"
					},
					{
						"name": "Last Day",
						"value": "last-day"
					},
					{
						"name": "Last Week",
						"value": "last-week"
					},
					{
						"name": "Last Month",
						"value": "last-month"
					},
					{
						"name": "Last Year",
						"value": "last-year"
					}
				],
				"default": "last-hour",
				"description": "Optional filter for when matching reels were posted.",
				"routing": {
					"send": {
						"type": "query",
						"property": "datePosted"
					}
				}
			},
			{
				"displayName": "Page",
				"name": "page",
				"type": "number",
				"default": 0,
				"description": "1-based results page number. Omit to request the first page. Pagination is page-based.",
				"routing": {
					"send": {
						"type": "query",
						"property": "page"
					}
				}
			}
		]
	}
];
