// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";

export const linktree: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"linktree"
				]
			}
		},
		"default": "linktree.profile.get",
		"options": [
			{
				"name": "Profile",
				"value": "linktree.profile.get",
				"action": "Get Linktree profile",
				"description": "Get a public Linktree profile by handle, including links and socials.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/linktree/profiles/{{$parameter[\"handle\"]}}"
					}
				}
			}
		]
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "Linktree handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"linktree"
				],
				"operation": [
					"linktree.profile.get"
				]
			}
		}
	}
];
