// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { cursorPagination } from "../shared/pagination";

export const linkedin: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				]
			}
		},
		"default": "linkedin.profile.get",
		"options": [
			{
				"name": "Profiles",
				"value": "linkedin.profile.get",
				"action": "Get LinkedIn profiles",
				"description": "Get LinkedIn person profiles by URL or handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/profiles"
					}
				}
			},
			{
				"name": "Profile Posts",
				"value": "linkedin.profiles.posts.list",
				"action": "List LinkedIn profile posts",
				"description": "List posts from a LinkedIn person profile.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/profiles/posts"
					}
				}
			},
			{
				"name": "People Search",
				"value": "linkedin.people.search.list",
				"action": "Search LinkedIn people",
				"description": "Search LinkedIn people by first and/or last name.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/people/search"
					}
				}
			},
			{
				"name": "Organization Page",
				"value": "linkedin.organization.get",
				"action": "Get LinkedIn organization page",
				"description": "Look up LinkedIn company, school, or organization pages by URL (broader than linkedin.company.get).",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/organizations"
					}
				}
			},
			{
				"name": "Company Page",
				"value": "linkedin.company.get",
				"action": "Get LinkedIn company page",
				"description": "Get a LinkedIn company page by company URL — use linkedin.organization.get for schools and mixed organization URLs.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/companies"
					}
				}
			},
			{
				"name": "Company Posts",
				"value": "linkedin.company.posts.list",
				"action": "List LinkedIn company posts",
				"description": "List posts from a LinkedIn company page.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/companies/posts"
					}
				}
			},
			{
				"name": "Post or Article",
				"value": "linkedin.post.get",
				"action": "Get LinkedIn post or article",
				"description": "Get a LinkedIn post or article by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/posts"
					}
				}
			},
			{
				"name": "Transcript",
				"value": "linkedin.post.transcript.get",
				"action": "Get LinkedIn post transcript",
				"description": "Get the transcript for a LinkedIn post video by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/posts/transcript"
					}
				}
			},
			{
				"name": "Post Search",
				"value": "linkedin.posts.search.list",
				"action": "Search LinkedIn posts",
				"description": "Search public LinkedIn posts by keyword.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/posts/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Ad Library Ad",
				"value": "linkedin.adLibrary.ad.get",
				"action": "Get LinkedIn Ad Library ad",
				"description": "Get a LinkedIn Ad Library ad by ad id or Ad Library URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/ad-library/ads"
					}
				}
			},
			{
				"name": "Ad Library Search",
				"value": "linkedin.adLibrary.ads.search.list",
				"action": "Search LinkedIn Ad Library ads",
				"description": "Search LinkedIn Ad Library ads by company, keyword, or company id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/ad-library/ads/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Jobs",
				"value": "linkedin.jobs.get",
				"action": "Get LinkedIn jobs",
				"description": "Get LinkedIn job postings by job URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/jobs"
					}
				}
			},
			{
				"name": "Job Search",
				"value": "linkedin.jobs.search.list",
				"action": "Search LinkedIn jobs",
				"description": "Search LinkedIn jobs by keyword and filters.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/jobs/search"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"typeOptions": {
			"multipleValues": true
		},
		"default": [],
		"description": "LinkedIn profile URL.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.profile.get"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "LinkedIn profile URL or vanity handle whose public posts should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.profiles.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.profiles.posts.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Start Date",
				"name": "startDate",
				"type": "string",
				"default": "",
				"description": "Optional start of the date range for posts to include.",
				"routing": {
					"send": {
						"type": "query",
						"property": "startDate"
					}
				}
			},
			{
				"displayName": "End Date",
				"name": "endDate",
				"type": "string",
				"default": "",
				"description": "Optional end of the date range for posts to include.",
				"routing": {
					"send": {
						"type": "query",
						"property": "endDate"
					}
				}
			},
			{
				"displayName": "Only Authored Posts",
				"name": "onlyAuthoredPosts",
				"type": "boolean",
				"default": false,
				"description": "When true, return only posts created by the profile owner.",
				"routing": {
					"send": {
						"type": "query",
						"property": "onlyAuthoredPosts"
					}
				}
			},
			{
				"displayName": "Limit",
				"name": "limit",
				"type": "number",
				"default": 10,
				"description": "Maximum posts to return (default 10).",
				"routing": {
					"send": {
						"type": "query",
						"property": "limit"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.people.search.list"
				]
			}
		},
		"options": [
			{
				"displayName": "First Name",
				"name": "firstName",
				"type": "string",
				"default": "",
				"description": "First name filter. At least one of `firstName` or `lastName` is required.",
				"routing": {
					"send": {
						"type": "query",
						"property": "firstName"
					}
				}
			},
			{
				"displayName": "Last Name",
				"name": "lastName",
				"type": "string",
				"default": "",
				"description": "Last name filter. At least one of `firstName` or `lastName` is required.",
				"routing": {
					"send": {
						"type": "query",
						"property": "lastName"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"typeOptions": {
			"multipleValues": true
		},
		"default": [],
		"description": "LinkedIn organization page URL.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.organization.get"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "LinkedIn company page URL for this lookup. School and organization-guest pages are not supported; use `GET /v1/linkedin/organizations`.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.company.get"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "LinkedIn company page URL or slug whose posts should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.company.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.company.posts.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Page",
				"name": "page",
				"type": "number",
				"default": 0,
				"description": "1-based results page number. Pagination is page-based; at most 7 pages can be requested for a given company.",
				"routing": {
					"send": {
						"type": "query",
						"property": "page"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public permalink to the post or article.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.post.get"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the LinkedIn post whose video transcript should be returned.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.post.transcript.get"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.posts.search.list"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Keyword or phrase to search for in public LinkedIn posts.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.posts.search.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.posts.search.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Date Posted",
				"name": "datePosted",
				"type": "options",
				"options": [
					{
						"name": "Last Hour",
						"value": "last-hour"
					},
					{
						"name": "Last Day",
						"value": "last-day"
					},
					{
						"name": "Last Week",
						"value": "last-week"
					},
					{
						"name": "Last Month",
						"value": "last-month"
					},
					{
						"name": "Last Year",
						"value": "last-year"
					}
				],
				"default": "last-hour",
				"description": "Optional filter for how recently matching posts were published.",
				"routing": {
					"send": {
						"type": "query",
						"property": "datePosted"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.adLibrary.ad.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Ad ID",
				"name": "adId",
				"type": "string",
				"default": "",
				"description": "LinkedIn Ad Library id for the ad.",
				"routing": {
					"send": {
						"type": "query",
						"property": "adId"
					}
				}
			},
			{
				"displayName": "URL",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Public LinkedIn Ad Library URL for the ad.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.adLibrary.ads.search.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.adLibrary.ads.search.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Company",
				"name": "company",
				"type": "string",
				"default": "",
				"description": "Company name to search for in the LinkedIn Ad Library.",
				"routing": {
					"send": {
						"type": "query",
						"property": "company"
					}
				}
			},
			{
				"displayName": "Keyword",
				"name": "keyword",
				"type": "string",
				"default": "",
				"description": "Keyword or phrase to search for in LinkedIn Ad Library ads.",
				"routing": {
					"send": {
						"type": "query",
						"property": "keyword"
					}
				}
			},
			{
				"displayName": "Company ID",
				"name": "companyId",
				"type": "string",
				"default": "",
				"description": "LinkedIn company id to search for in the Ad Library.",
				"routing": {
					"send": {
						"type": "query",
						"property": "companyId"
					}
				}
			},
			{
				"displayName": "Countries",
				"name": "countries",
				"type": "string",
				"default": "",
				"description": "Optional comma-separated list of country codes (for example US,CA,MX).",
				"routing": {
					"send": {
						"type": "query",
						"property": "countries"
					}
				}
			},
			{
				"displayName": "Start Date",
				"name": "startDate",
				"type": "string",
				"default": "",
				"description": "Optional start date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "startDate"
					}
				}
			},
			{
				"displayName": "End Date",
				"name": "endDate",
				"type": "string",
				"default": "",
				"description": "Optional end date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "endDate"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"typeOptions": {
			"multipleValues": true
		},
		"default": [],
		"description": "LinkedIn job posting URL to look up.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.jobs.get"
				]
			}
		}
	},
	{
		"displayName": "Keyword",
		"name": "keyword",
		"type": "string",
		"default": "",
		"description": "Search keyword for LinkedIn job listings.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "keyword"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.jobs.search.list"
				]
			}
		}
	},
	{
		"displayName": "Location",
		"name": "location",
		"type": "string",
		"default": "",
		"description": "Location label for the search.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "location"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.jobs.search.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.jobs.search.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Country",
				"name": "country",
				"type": "string",
				"default": "",
				"description": "Optional ISO 3166-1 country code.",
				"routing": {
					"send": {
						"type": "query",
						"property": "country"
					}
				}
			},
			{
				"displayName": "Time Range",
				"name": "timeRange",
				"type": "options",
				"options": [
					{
						"name": "Any",
						"value": "any"
					},
					{
						"name": "Past Month",
						"value": "past-month"
					},
					{
						"name": "Past Week",
						"value": "past-week"
					},
					{
						"name": "Past 24 Hours",
						"value": "past-24-hours"
					}
				],
				"default": "any",
				"description": "Optional time range filter for when jobs were posted.",
				"routing": {
					"send": {
						"type": "query",
						"property": "timeRange"
					}
				}
			},
			{
				"displayName": "Job Type",
				"name": "jobType",
				"type": "options",
				"options": [
					{
						"name": "Full Time",
						"value": "full-time"
					},
					{
						"name": "Part Time",
						"value": "part-time"
					},
					{
						"name": "Contract",
						"value": "contract"
					},
					{
						"name": "Temporary",
						"value": "temporary"
					},
					{
						"name": "Volunteer",
						"value": "volunteer"
					}
				],
				"default": "full-time",
				"description": "Optional job type filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "jobType"
					}
				}
			},
			{
				"displayName": "Experience Level",
				"name": "experienceLevel",
				"type": "options",
				"options": [
					{
						"name": "Internship",
						"value": "internship"
					},
					{
						"name": "Entry Level",
						"value": "entry-level"
					},
					{
						"name": "Associate",
						"value": "associate"
					},
					{
						"name": "Mid Senior Level",
						"value": "mid-senior-level"
					},
					{
						"name": "Director",
						"value": "director"
					},
					{
						"name": "Executive",
						"value": "executive"
					}
				],
				"default": "internship",
				"description": "Optional experience level filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "experienceLevel"
					}
				}
			},
			{
				"displayName": "Remote",
				"name": "remote",
				"type": "options",
				"options": [
					{
						"name": "On Site",
						"value": "on-site"
					},
					{
						"name": "Remote",
						"value": "remote"
					},
					{
						"name": "Hybrid",
						"value": "hybrid"
					}
				],
				"default": "on-site",
				"description": "Optional work arrangement filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "remote"
					}
				}
			},
			{
				"displayName": "Company",
				"name": "company",
				"type": "string",
				"default": "",
				"description": "Optional company name filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "company"
					}
				}
			},
			{
				"displayName": "Location Radius",
				"name": "locationRadius",
				"type": "options",
				"options": [
					{
						"name": "Exact Location",
						"value": "exact-location"
					},
					{
						"name": "5 Miles",
						"value": "5-miles"
					},
					{
						"name": "10 Miles",
						"value": "10-miles"
					},
					{
						"name": "25 Miles",
						"value": "25-miles"
					},
					{
						"name": "50 Miles",
						"value": "50-miles"
					}
				],
				"default": "exact-location",
				"description": "Optional location radius filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "locationRadius"
					}
				}
			},
			{
				"displayName": "Limit",
				"name": "limit",
				"type": "number",
				"default": 10,
				"description": "Maximum job listings to return (default 10).",
				"routing": {
					"send": {
						"type": "query",
						"property": "limit"
					}
				}
			}
		]
	}
];
