// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";

export const linkedin: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				]
			}
		},
		"default": "linkedin.profile.get",
		"options": [
			{
				"name": "Profile",
				"value": "linkedin.profile.get",
				"action": "Get LinkedIn profile",
				"description": "Get a LinkedIn profile.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/profiles"
					}
				}
			},
			{
				"name": "Company page",
				"value": "linkedin.company.get",
				"action": "Get LinkedIn company page",
				"description": "Get a LinkedIn company page.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/companies"
					}
				}
			},
			{
				"name": "Company posts",
				"value": "linkedin.company.posts.list",
				"action": "List LinkedIn company posts",
				"description": "Get posts from a LinkedIn company page.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/companies/posts"
					}
				}
			},
			{
				"name": "Post or article",
				"value": "linkedin.post.get",
				"action": "Get LinkedIn post or article",
				"description": "Get a LinkedIn post or article.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/linkedin/posts"
					}
				}
			}
		]
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "LinkedIn public profile URL for this lookup.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.profile.get"
				]
			}
		}
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "LinkedIn company page URL for this lookup.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.company.get"
				]
			}
		}
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public LinkedIn company page URL for the organization whose posts should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.company.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.company.posts.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Page",
				"name": "page",
				"type": "number",
				"default": 0,
				"description": "1-based results page number. Pagination is page-based; at most 7 pages can be requested for a given company.",
				"routing": {
					"send": {
						"type": "query",
						"property": "page"
					}
				}
			}
		]
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public permalink to the post or article.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"linkedin"
				],
				"operation": [
					"linkedin.post.get"
				]
			}
		}
	}
];
