// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { cursorPagination } from "../shared/pagination";

export const reddit: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				]
			}
		},
		"default": "reddit.subreddit.get",
		"options": [
			{
				"name": "Subreddit",
				"value": "reddit.subreddit.get",
				"action": "Get Reddit subreddit",
				"description": "Get details for a Reddit community.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/reddit/subreddits"
					}
				}
			},
			{
				"name": "Search",
				"value": "reddit.search.list",
				"action": "Search Reddit posts",
				"description": "Search for posts on Reddit.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/reddit/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Subreddit posts",
				"value": "reddit.subreddit.posts.list",
				"action": "List Reddit subreddit posts",
				"description": "Get posts from a specific subreddit.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/reddit/subreddits/{{$parameter[\"subreddit\"]}}/posts"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Subreddit search",
				"value": "reddit.subreddit.search.list",
				"action": "Search Reddit subreddit",
				"description": "Search posts within a subreddit.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/reddit/subreddits/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Post comments",
				"value": "reddit.post.comments.list",
				"action": "List Reddit post comments",
				"description": "Get comments on a Reddit post.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/reddit/posts/comments"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.subreddit.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Subreddit",
				"name": "subreddit",
				"type": "string",
				"default": "",
				"description": "Subreddit name, optional `r/` prefix, or Reddit subreddit URL. Must match Reddit's exact casing (for example `AskReddit`, not `askreddit`).",
				"routing": {
					"send": {
						"type": "query",
						"property": "subreddit"
					}
				}
			},
			{
				"displayName": "Url",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Optional subreddit URL for the request.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.search.list"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for public Reddit posts.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.search.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.search.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Sort By",
				"name": "sortBy",
				"type": "options",
				"options": [
					{
						"name": "Relevance",
						"value": "relevance"
					},
					{
						"name": "New",
						"value": "new"
					},
					{
						"name": "Top",
						"value": "top"
					}
				],
				"default": "relevance",
				"description": "Optional sort order for search results.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sortBy"
					}
				}
			},
			{
				"displayName": "Timeframe",
				"name": "timeframe",
				"type": "options",
				"options": [
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Day",
						"value": "day"
					},
					{
						"name": "Week",
						"value": "week"
					},
					{
						"name": "Month",
						"value": "month"
					},
					{
						"name": "Year",
						"value": "year"
					}
				],
				"default": "all",
				"description": "Optional time range filter for search results.",
				"routing": {
					"send": {
						"type": "query",
						"property": "timeframe"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "Whether to request a smaller response shape when available.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.subreddit.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Subreddit",
		"name": "subreddit",
		"type": "string",
		"default": "",
		"description": "Subreddit name, optional `r/` prefix, or Reddit subreddit URL. Must match Reddit's exact casing (for example `AskReddit`, not `askreddit`). Lists posts for this subreddit.",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.subreddit.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.subreddit.posts.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Sort",
				"name": "sort",
				"type": "options",
				"options": [
					{
						"name": "Best",
						"value": "best"
					},
					{
						"name": "Hot",
						"value": "hot"
					},
					{
						"name": "New",
						"value": "new"
					},
					{
						"name": "Top",
						"value": "top"
					},
					{
						"name": "Rising",
						"value": "rising"
					}
				],
				"default": "best",
				"description": "Optional sort order for the returned posts.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sort"
					}
				}
			},
			{
				"displayName": "Timeframe",
				"name": "timeframe",
				"type": "options",
				"options": [
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Day",
						"value": "day"
					},
					{
						"name": "Week",
						"value": "week"
					},
					{
						"name": "Month",
						"value": "month"
					},
					{
						"name": "Year",
						"value": "year"
					}
				],
				"default": "all",
				"description": "Optional timeframe used with time-based sort orders.",
				"routing": {
					"send": {
						"type": "query",
						"property": "timeframe"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.subreddit.search.list"
				]
			}
		}
	},
	{
		"displayName": "Subreddit",
		"name": "subreddit",
		"type": "string",
		"default": "",
		"description": "Subreddit name, optional `r/` prefix, or Reddit subreddit URL. Must match Reddit's exact casing (for example `AskReddit`, not `askreddit`). Searches posts within this subreddit.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "subreddit"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.subreddit.search.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.subreddit.search.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Query",
				"name": "query",
				"type": "string",
				"default": "",
				"description": "Search text to match against public subreddit posts.",
				"placeholder": "e.g. automation",
				"routing": {
					"send": {
						"type": "query",
						"property": "query"
					}
				}
			},
			{
				"displayName": "Sort",
				"name": "sort",
				"type": "options",
				"options": [
					{
						"name": "Relevance",
						"value": "relevance"
					},
					{
						"name": "Hot",
						"value": "hot"
					},
					{
						"name": "Top",
						"value": "top"
					},
					{
						"name": "New",
						"value": "new"
					},
					{
						"name": "Comments",
						"value": "comments"
					}
				],
				"default": "relevance",
				"description": "Optional sort order for search results. Defaults to relevance when omitted.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sort"
					}
				}
			},
			{
				"displayName": "Timeframe",
				"name": "timeframe",
				"type": "options",
				"options": [
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Year",
						"value": "year"
					},
					{
						"name": "Month",
						"value": "month"
					},
					{
						"name": "Week",
						"value": "week"
					},
					{
						"name": "Day",
						"value": "day"
					},
					{
						"name": "Hour",
						"value": "hour"
					}
				],
				"default": "all",
				"description": "Optional time range filter for search results. Defaults to all when omitted.",
				"routing": {
					"send": {
						"type": "query",
						"property": "timeframe"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.post.comments.list"
				]
			}
		}
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the Reddit post whose comments should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.post.comments.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"reddit"
				],
				"operation": [
					"reddit.post.comments.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, requests a lighter response shape when available.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	}
];
