// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";

export const spotify: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"spotify"
				]
			}
		},
		"default": "spotify.artist.get",
		"options": [
			{
				"name": "Artist",
				"value": "spotify.artist.get",
				"action": "Get Spotify artist",
				"description": "Get a Spotify artist by id or profile URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/spotify/artist"
					}
				}
			},
			{
				"name": "Album",
				"value": "spotify.album.get",
				"action": "Get Spotify album",
				"description": "Get a Spotify album by id or album URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/spotify/album"
					}
				}
			},
			{
				"name": "Track",
				"value": "spotify.track.get",
				"action": "Get Spotify track",
				"description": "Get a Spotify track by id or track URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/spotify/track"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"spotify"
				],
				"operation": [
					"spotify.artist.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Artist Id",
				"name": "artistId",
				"type": "string",
				"default": "",
				"description": "Optional Spotify artist id for the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "artistId"
					}
				}
			},
			{
				"displayName": "Url",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Optional Spotify artist URL for the request.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"spotify"
				],
				"operation": [
					"spotify.album.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Album Id",
				"name": "albumId",
				"type": "string",
				"default": "",
				"description": "Optional Spotify album id for the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "albumId"
					}
				}
			},
			{
				"displayName": "Url",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Optional Spotify album URL for the request.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"spotify"
				],
				"operation": [
					"spotify.track.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Track Id",
				"name": "trackId",
				"type": "string",
				"default": "",
				"description": "Optional Spotify track id for the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trackId"
					}
				}
			},
			{
				"displayName": "Url",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Optional Spotify track URL for the request.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			}
		]
	}
];
