// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { cursorPagination } from "../shared/pagination";

export const telegram: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"telegram"
				]
			}
		},
		"default": "telegram.channel.get",
		"options": [
			{
				"name": "Channel",
				"value": "telegram.channel.get",
				"action": "Get Telegram channel",
				"description": "Get metadata for a public Telegram channel or group by username.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/telegram/channels/{{$parameter[\"handle\"]}}"
					}
				}
			},
			{
				"name": "Channel Posts",
				"value": "telegram.channel_posts.get",
				"action": "List Telegram channel posts",
				"description": "List recent posts from a public Telegram channel. Groups are not supported.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/telegram/channels/{{$parameter[\"handle\"]}}/posts"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Channel Post",
				"value": "telegram.channel_post.get",
				"action": "Get Telegram channel post",
				"description": "Get a single public post from a Telegram channel by handle and post ID. Groups are not supported.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/telegram/channels/{{$parameter[\"handle\"]}}/posts/{{$parameter[\"postId\"]}}"
					}
				}
			}
		]
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "Telegram public username (channel or group), with or without leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"telegram"
				],
				"operation": [
					"telegram.channel.get"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"telegram"
				],
				"operation": [
					"telegram.channel_posts.get"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "Telegram public username (channel or group), with or without leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"telegram"
				],
				"operation": [
					"telegram.channel_posts.get"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "Telegram public username (channel or group), with or without leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"telegram"
				],
				"operation": [
					"telegram.channel_post.get"
				]
			}
		}
	},
	{
		"displayName": "Post ID",
		"name": "postId",
		"type": "string",
		"default": "",
		"description": "Numeric Telegram channel post ID from the public URL.",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"telegram"
				],
				"operation": [
					"telegram.channel_post.get"
				]
			}
		}
	}
];
