// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";

export const threads: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"threads"
				]
			}
		},
		"default": "threads.profile.get",
		"options": [
			{
				"name": "Profile",
				"value": "threads.profile.get",
				"action": "Get Threads profile",
				"description": "Get a Threads profile for a creator or account.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/threads/profiles/{{$parameter[\"handle\"]}}"
					}
				}
			},
			{
				"name": "Profile Posts",
				"value": "threads.profile.posts.list",
				"action": "List Threads profile posts",
				"description": "Get posts from a specific Threads profile.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/threads/profiles/{{$parameter[\"handle\"]}}/posts"
					}
				}
			},
			{
				"name": "Search Posts",
				"value": "threads.search.list",
				"action": "Search Threads posts",
				"description": "Search for posts on Threads.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/threads/search"
					}
				}
			},
			{
				"name": "Post",
				"value": "threads.post.get",
				"action": "Get Threads post",
				"description": "Get a single Threads post.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/threads/posts"
					}
				}
			},
			{
				"name": "User Search",
				"value": "threads.users.search",
				"action": "Search Threads users",
				"description": "Search for users on Threads.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/threads/users/search"
					}
				}
			}
		]
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "Threads handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"threads"
				],
				"operation": [
					"threads.profile.get"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "Threads handle whose posts should be listed.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"threads"
				],
				"operation": [
					"threads.profile.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"threads"
				],
				"operation": [
					"threads.profile.posts.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, returns a smaller response with fewer post fields when available.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for public Threads posts.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"threads"
				],
				"operation": [
					"threads.search.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"threads"
				],
				"operation": [
					"threads.search.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Start Date",
				"name": "startDate",
				"type": "string",
				"default": "",
				"description": "Optional start date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "startDate"
					}
				}
			},
			{
				"displayName": "End Date",
				"name": "endDate",
				"type": "string",
				"default": "",
				"description": "Optional end date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "endDate"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "Whether to request a smaller response shape when available.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the Threads post.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"threads"
				],
				"operation": [
					"threads.post.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"threads"
				],
				"operation": [
					"threads.post.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, returns a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for Threads users.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"threads"
				],
				"operation": [
					"threads.users.search"
				]
			}
		}
	}
];
