// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { cursorPagination } from "../shared/pagination";

export const tiktok: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				]
			}
		},
		"default": "tiktok.profile.get",
		"options": [
			{
				"name": "Profile",
				"value": "tiktok.profile.get",
				"action": "Get TikTok profile",
				"description": "Get a TikTok profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}"
					}
				}
			},
			{
				"name": "Profile Videos",
				"value": "tiktok.profile.videos.list",
				"action": "List TikTok profile videos",
				"description": "List videos from a TikTok profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/videos"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Profile Followers",
				"value": "tiktok.profile.followers.list",
				"action": "List TikTok profile followers",
				"description": "List followers of a TikTok profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/followers"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Profile Following",
				"value": "tiktok.profile.following.list",
				"action": "List TikTok profile following",
				"description": "List accounts followed by a TikTok profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/following"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Profile Region",
				"value": "tiktok.profile.region.get",
				"action": "Get TikTok profile region",
				"description": "Get the region code reported for a TikTok profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/region"
					}
				}
			},
			{
				"name": "Profile Audience",
				"value": "tiktok.profile.audience.get",
				"action": "Get TikTok profile audience",
				"description": "Get audience location demographics for a TikTok profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/audience"
					}
				}
			},
			{
				"name": "Live Stream",
				"value": "tiktok.profile.live.check",
				"action": "Get TikTok live stream",
				"description": "Check whether a TikTok creator is currently live by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/live"
					}
				}
			},
			{
				"name": "User Search",
				"value": "tiktok.users.search",
				"action": "Search TikTok users",
				"description": "Search TikTok users by keyword.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/users/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Search Videos",
				"value": "tiktok.search.videos.list",
				"action": "Search TikTok videos",
				"description": "Search TikTok videos by keyword.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Hashtag Search",
				"value": "tiktok.search.hashtag.list",
				"action": "Search TikTok by hashtag",
				"description": "Search TikTok videos by hashtag (not free-text keyword — use tiktok.search.videos.list for that).",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/search/hashtags"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Video",
				"value": "tiktok.video.get",
				"action": "Get TikTok video",
				"description": "Get a single TikTok video by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/videos"
					}
				}
			},
			{
				"name": "Comments",
				"value": "tiktok.video.comments.list",
				"action": "List TikTok video comments",
				"description": "List comments on a TikTok video by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/videos/comments"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Transcript",
				"value": "tiktok.video.transcript.get",
				"action": "Get TikTok video transcript",
				"description": "Get the spoken transcript for a TikTok video by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/videos/transcript"
					}
				}
			},
			{
				"name": "Trending Feed",
				"value": "tiktok.feed.trending.list",
				"action": "List TikTok trending feed",
				"description": "List currently trending TikTok posts for a region.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/feed/trending"
					}
				}
			},
			{
				"name": "Shop Product Search",
				"value": "tiktok.shop.products.search",
				"action": "Search TikTok Shop products",
				"description": "Search products in TikTok Shop by keyword.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/shop/products/search"
					}
				}
			},
			{
				"name": "Shop Store Products",
				"value": "tiktok.shop.products.list",
				"action": "List TikTok Shop store products",
				"description": "List products in a TikTok Shop store by shop id or URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/shop/products"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Shop Product",
				"value": "tiktok.product.get",
				"action": "Get TikTok Shop product",
				"description": "Get details for a TikTok Shop product by product id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/products"
					}
				}
			},
			{
				"name": "Shop Product Reviews",
				"value": "tiktok.product.reviews.list",
				"action": "List TikTok Shop product reviews",
				"description": "List buyer reviews for a TikTok Shop product by product id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/products/reviews"
					}
				}
			},
			{
				"name": "Profile Showcase Products",
				"value": "tiktok.profile.showcaseProducts.list",
				"action": "List TikTok profile showcase products",
				"description": "List products featured on a creator's TikTok showcase by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/showcase-products"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			}
		]
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.get"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.videos.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle whose videos should be listed.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.videos.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.videos.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Sort By",
				"name": "sortBy",
				"type": "options",
				"options": [
					{
						"name": "Latest",
						"value": "latest"
					},
					{
						"name": "Popular",
						"value": "popular"
					}
				],
				"default": "latest",
				"description": "Optional sort order for the returned TikTok videos.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sortBy"
					}
				}
			},
			{
				"displayName": "User ID",
				"name": "userId",
				"type": "string",
				"default": "",
				"description": "Optional TikTok user id to speed up the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "userId"
					}
				}
			},
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional ISO 3166-1 country code for the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "Optional flag for a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.followers.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle whose followers should be listed.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.followers.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.followers.list"
				]
			}
		},
		"options": [
			{
				"displayName": "User ID",
				"name": "userId",
				"type": "string",
				"default": "",
				"description": "Optional TikTok user id to speed up the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "userId"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "Optional flag for a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.following.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle whose following list should be listed.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.following.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.following.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "Optional flag for a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.region.get"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.audience.get"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.live.check"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.users.search"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for TikTok users.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.users.search"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.search.videos.list"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for TikTok videos.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.search.videos.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.search.videos.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Date Posted",
				"name": "datePosted",
				"type": "options",
				"options": [
					{
						"name": "Yesterday",
						"value": "yesterday"
					},
					{
						"name": "This Week",
						"value": "this-week"
					},
					{
						"name": "This Month",
						"value": "this-month"
					},
					{
						"name": "Last 3 Months",
						"value": "last-3-months"
					},
					{
						"name": "Last 6 Months",
						"value": "last-6-months"
					},
					{
						"name": "All Time",
						"value": "all-time"
					}
				],
				"default": "yesterday",
				"description": "Optional upload date filter for video results.",
				"routing": {
					"send": {
						"type": "query",
						"property": "datePosted"
					}
				}
			},
			{
				"displayName": "Sort By",
				"name": "sortBy",
				"type": "options",
				"options": [
					{
						"name": "Relevance",
						"value": "relevance"
					},
					{
						"name": "Most Liked",
						"value": "most-liked"
					},
					{
						"name": "Date Posted",
						"value": "date-posted"
					}
				],
				"default": "relevance",
				"description": "Optional sort order for search results.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sortBy"
					}
				}
			},
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional two-letter ISO 3166-1 country code for localized search results.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, returns a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.search.hashtag.list"
				]
			}
		}
	},
	{
		"displayName": "Hashtag",
		"name": "hashtag",
		"type": "string",
		"default": "",
		"description": "Hashtag to search for. A leading # is optional.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "hashtag"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.search.hashtag.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.search.hashtag.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional ISO 3166-1 country code for the request. This sets the proxy region and does not filter results to that country only.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "Whether to request a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the video or photo post.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional ISO 3166-1 country code used to route the request when needed.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, returns a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			},
			{
				"displayName": "Download Media",
				"name": "downloadMedia",
				"type": "boolean",
				"default": false,
				"description": "When true, includes hosted CDN URLs in `downloads` when available. Adds 10 credits (11 total with the base lookup) on successful lookups, even if `downloads` is empty.",
				"routing": {
					"send": {
						"type": "query",
						"property": "downloadMedia"
					}
				}
			},
			{
				"displayName": "Get Transcript",
				"name": "getTranscript",
				"type": "boolean",
				"default": false,
				"description": "When true, includes the video transcript (WEBVTT) in `transcript` when one is available.",
				"routing": {
					"send": {
						"type": "query",
						"property": "getTranscript"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.comments.list"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the TikTok video whose comments should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.comments.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.comments.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, returns a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the TikTok video whose transcript should be returned.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.transcript.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.transcript.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Language",
				"name": "language",
				"type": "string",
				"default": "",
				"description": "Optional two-letter language code to request a transcript in a specific language when available.",
				"routing": {
					"send": {
						"type": "query",
						"property": "language"
					}
				}
			},
			{
				"displayName": "Use AI Fallback",
				"name": "useAiFallback",
				"type": "boolean",
				"default": false,
				"description": "When true, uses Social Fetch's AI fallback when a transcript is not otherwise available. Adds 10 credits on completed lookups (11 total with the base lookup).",
				"routing": {
					"send": {
						"type": "query",
						"property": "useAiFallback"
					}
				}
			}
		]
	},
	{
		"displayName": "Region",
		"name": "region",
		"type": "string",
		"default": "",
		"description": "Two-letter ISO 3166-1 country code for the request.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "region"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.feed.trending.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.feed.trending.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, requests a smaller response with fewer optional fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for TikTok Shop products.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.shop.products.search"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.shop.products.search"
				]
			}
		},
		"options": [
			{
				"displayName": "Page",
				"name": "page",
				"type": "number",
				"default": 0,
				"description": "1-based results page number. Omit to request the first page. Pagination is page-based.",
				"routing": {
					"send": {
						"type": "query",
						"property": "page"
					}
				}
			},
			{
				"displayName": "Region",
				"name": "region",
				"type": "options",
				"options": [
					{
						"name": "US",
						"value": "US"
					},
					{
						"name": "GB",
						"value": "GB"
					},
					{
						"name": "DE",
						"value": "DE"
					},
					{
						"name": "FR",
						"value": "FR"
					},
					{
						"name": "IT",
						"value": "IT"
					},
					{
						"name": "ID",
						"value": "ID"
					},
					{
						"name": "MY",
						"value": "MY"
					},
					{
						"name": "MX",
						"value": "MX"
					},
					{
						"name": "PH",
						"value": "PH"
					},
					{
						"name": "SG",
						"value": "SG"
					},
					{
						"name": "ES",
						"value": "ES"
					},
					{
						"name": "TH",
						"value": "TH"
					},
					{
						"name": "VN",
						"value": "VN"
					},
					{
						"name": "BR",
						"value": "BR"
					},
					{
						"name": "JP",
						"value": "JP"
					},
					{
						"name": "IE",
						"value": "IE"
					}
				],
				"default": "US",
				"description": "Optional country or region code for the product search catalog.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.shop.products.list"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public TikTok Shop store URL whose products should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.shop.products.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.shop.products.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "options",
				"options": [
					{
						"name": "US",
						"value": "US"
					},
					{
						"name": "GB",
						"value": "GB"
					},
					{
						"name": "DE",
						"value": "DE"
					},
					{
						"name": "FR",
						"value": "FR"
					},
					{
						"name": "IT",
						"value": "IT"
					},
					{
						"name": "ID",
						"value": "ID"
					},
					{
						"name": "MY",
						"value": "MY"
					},
					{
						"name": "MX",
						"value": "MX"
					},
					{
						"name": "PH",
						"value": "PH"
					},
					{
						"name": "SG",
						"value": "SG"
					},
					{
						"name": "ES",
						"value": "ES"
					},
					{
						"name": "TH",
						"value": "TH"
					},
					{
						"name": "VN",
						"value": "VN"
					},
					{
						"name": "BR",
						"value": "BR"
					},
					{
						"name": "JP",
						"value": "JP"
					},
					{
						"name": "IE",
						"value": "IE"
					}
				],
				"default": "US",
				"description": "Optional region code for the shop catalog. When omitted, the default catalog region is US.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public TikTok Shop product detail page URL for the product to retrieve.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.product.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.product.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "options",
				"options": [
					{
						"name": "US",
						"value": "US"
					},
					{
						"name": "GB",
						"value": "GB"
					},
					{
						"name": "DE",
						"value": "DE"
					},
					{
						"name": "FR",
						"value": "FR"
					},
					{
						"name": "IT",
						"value": "IT"
					},
					{
						"name": "ID",
						"value": "ID"
					},
					{
						"name": "MY",
						"value": "MY"
					},
					{
						"name": "MX",
						"value": "MX"
					},
					{
						"name": "PH",
						"value": "PH"
					},
					{
						"name": "SG",
						"value": "SG"
					},
					{
						"name": "ES",
						"value": "ES"
					},
					{
						"name": "TH",
						"value": "TH"
					},
					{
						"name": "VN",
						"value": "VN"
					},
					{
						"name": "BR",
						"value": "BR"
					},
					{
						"name": "JP",
						"value": "JP"
					},
					{
						"name": "IE",
						"value": "IE"
					}
				],
				"default": "US",
				"description": "Optional country or region code for the product catalog. When omitted, the default catalog region applies.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.product.reviews.list"
				]
			}
		},
		"options": [
			{
				"displayName": "URL",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Public TikTok Shop product detail page URL for the product whose reviews should be listed.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			},
			{
				"displayName": "Product ID",
				"name": "productId",
				"type": "string",
				"default": "",
				"description": "TikTok Shop product identifier. Provide this instead of `url` when you already know the product id.",
				"routing": {
					"send": {
						"type": "query",
						"property": "productId"
					}
				}
			},
			{
				"displayName": "Region",
				"name": "region",
				"type": "options",
				"options": [
					{
						"name": "US",
						"value": "US"
					},
					{
						"name": "GB",
						"value": "GB"
					},
					{
						"name": "DE",
						"value": "DE"
					},
					{
						"name": "FR",
						"value": "FR"
					},
					{
						"name": "IT",
						"value": "IT"
					},
					{
						"name": "ID",
						"value": "ID"
					},
					{
						"name": "MY",
						"value": "MY"
					},
					{
						"name": "MX",
						"value": "MX"
					},
					{
						"name": "PH",
						"value": "PH"
					},
					{
						"name": "SG",
						"value": "SG"
					},
					{
						"name": "ES",
						"value": "ES"
					},
					{
						"name": "TH",
						"value": "TH"
					},
					{
						"name": "VN",
						"value": "VN"
					},
					{
						"name": "BR",
						"value": "BR"
					},
					{
						"name": "JP",
						"value": "JP"
					},
					{
						"name": "IE",
						"value": "IE"
					}
				],
				"default": "US",
				"description": "Optional country or region code for the product review catalog. When omitted, the default catalog region applies.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Page",
				"name": "page",
				"type": "number",
				"default": 0,
				"description": "1-based review page number. Omit to request the first page.",
				"routing": {
					"send": {
						"type": "query",
						"property": "page"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.showcaseProducts.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle whose profile showcase products should be listed.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.showcaseProducts.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.showcaseProducts.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional ISO 3166-1 country code for the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			}
		]
	}
];
