// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { cursorPagination } from "../shared/pagination";

export const tiktok: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				]
			}
		},
		"default": "tiktok.profile.get",
		"options": [
			{
				"name": "Profile",
				"value": "tiktok.profile.get",
				"action": "Get TikTok profile",
				"description": "Get a TikTok profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}"
					}
				}
			},
			{
				"name": "Profile Videos",
				"value": "tiktok.profile.videos.list",
				"action": "List TikTok profile videos",
				"description": "List videos from a TikTok profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/videos"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Profile Followers",
				"value": "tiktok.profile.followers.list",
				"action": "List TikTok profile followers",
				"description": "List followers of a TikTok profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/followers"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Profile Following",
				"value": "tiktok.profile.following.list",
				"action": "List TikTok profile following",
				"description": "List accounts followed by a TikTok profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/following"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Profile Region",
				"value": "tiktok.profile.region.get",
				"action": "Get TikTok profile region",
				"description": "Get the region code reported for a TikTok profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/region"
					}
				}
			},
			{
				"name": "Profile Audience",
				"value": "tiktok.profile.audience.get",
				"action": "Get TikTok profile audience",
				"description": "Get audience location demographics for a TikTok profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/audience"
					}
				}
			},
			{
				"name": "Live Stream",
				"value": "tiktok.profile.live.check",
				"action": "Get TikTok live stream",
				"description": "Check whether a TikTok creator is currently live by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/live"
					}
				}
			},
			{
				"name": "User Search",
				"value": "tiktok.users.search",
				"action": "Search TikTok users",
				"description": "Search TikTok users by keyword.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/users/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Search Videos",
				"value": "tiktok.search.videos.list",
				"action": "Search TikTok videos",
				"description": "Search TikTok videos by keyword.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Hashtag Search",
				"value": "tiktok.search.hashtag.list",
				"action": "Search TikTok by hashtag",
				"description": "Search TikTok videos by hashtag (not free-text keyword — use tiktok.search.videos.list for that).",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/search/hashtags"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Video",
				"value": "tiktok.video.get",
				"action": "Get TikTok video",
				"description": "Get a single TikTok video by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/videos"
					}
				}
			},
			{
				"name": "Comments",
				"value": "tiktok.video.comments.list",
				"action": "List TikTok video comments",
				"description": "List comments on a TikTok video by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/videos/comments"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Replies",
				"value": "tiktok.video.comments.replies.list",
				"action": "List TikTok comment replies",
				"description": "List replies to a TikTok video comment.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/videos/comments/replies"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Transcript",
				"value": "tiktok.video.transcript.get",
				"action": "Get TikTok video transcript",
				"description": "Get the spoken transcript for a TikTok video by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/videos/transcript"
					}
				}
			},
			{
				"name": "Trending Feed",
				"value": "tiktok.feed.trending.list",
				"action": "List TikTok trending feed",
				"description": "List currently trending TikTok posts for a region.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/feed/trending"
					}
				}
			},
			{
				"name": "Song",
				"value": "tiktok.song.get",
				"action": "Get TikTok song",
				"description": "Get details for a TikTok song or sound by id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/songs"
					}
				}
			},
			{
				"name": "Music Videos",
				"value": "tiktok.music.videos.list",
				"action": "List TikTok music videos",
				"description": "List TikTok videos that use a specific music clip.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/music/{{$parameter[\"clipId\"]}}/videos"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Shop Product Search",
				"value": "tiktok.shop.products.search",
				"action": "Search TikTok Shop products",
				"description": "Search products in TikTok Shop by keyword.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/shop/products/search"
					}
				}
			},
			{
				"name": "Shop Store Products",
				"value": "tiktok.shop.products.list",
				"action": "List TikTok Shop store products",
				"description": "List products in a TikTok Shop store by shop id or URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/shop/products"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Shop Product",
				"value": "tiktok.product.get",
				"action": "Get TikTok Shop product",
				"description": "Get details for a TikTok Shop product by product id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/products"
					}
				}
			},
			{
				"name": "Shop Product Reviews",
				"value": "tiktok.product.reviews.list",
				"action": "List TikTok Shop product reviews",
				"description": "List buyer reviews for a TikTok Shop product by product id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/products/reviews"
					}
				}
			},
			{
				"name": "Profile Showcase Products",
				"value": "tiktok.profile.showcaseProducts.list",
				"action": "List TikTok profile showcase products",
				"description": "List products featured on a creator's TikTok showcase by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/tiktok/profiles/{{$parameter[\"handle\"]}}/showcase-products"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Ad Library Ad",
				"value": "tiktok.adLibrary.ad.get",
				"action": "Get TikTok Ad Library ad",
				"description": "Get a single TikTok Ad Library or Top Ads creative by ad id or public ad URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/ad-library/ads"
					}
				}
			},
			{
				"name": "Ad Library Search",
				"value": "tiktok.adLibrary.ads.search.get",
				"action": "Search TikTok Ad Library ads",
				"description": "Search TikTok Top Ads by keyword and filters, or search the public Ads Library by advertiser name.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/tiktok/ad-library/ads/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			}
		]
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.get"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.videos.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle whose videos should be listed.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.videos.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.videos.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Sort By",
				"name": "sortBy",
				"type": "options",
				"options": [
					{
						"name": "Latest",
						"value": "latest"
					},
					{
						"name": "Popular",
						"value": "popular"
					}
				],
				"default": "latest",
				"description": "Optional sort order for the returned TikTok videos.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sortBy"
					}
				}
			},
			{
				"displayName": "User ID",
				"name": "userId",
				"type": "string",
				"default": "",
				"description": "Optional TikTok user id to speed up the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "userId"
					}
				}
			},
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional ISO 3166-1 country code for the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "Optional flag for a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.followers.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle whose followers should be listed.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.followers.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.followers.list"
				]
			}
		},
		"options": [
			{
				"displayName": "User ID",
				"name": "userId",
				"type": "string",
				"default": "",
				"description": "Optional TikTok user id to speed up the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "userId"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "Optional flag for a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.following.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle whose following list should be listed.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.following.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.following.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "Optional flag for a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.region.get"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.audience.get"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.live.check"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.users.search"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for TikTok users.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.users.search"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.search.videos.list"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for TikTok videos.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.search.videos.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.search.videos.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Date Posted",
				"name": "datePosted",
				"type": "options",
				"options": [
					{
						"name": "Yesterday",
						"value": "yesterday"
					},
					{
						"name": "This Week",
						"value": "this-week"
					},
					{
						"name": "This Month",
						"value": "this-month"
					},
					{
						"name": "Last 3 Months",
						"value": "last-3-months"
					},
					{
						"name": "Last 6 Months",
						"value": "last-6-months"
					},
					{
						"name": "All Time",
						"value": "all-time"
					}
				],
				"default": "yesterday",
				"description": "Optional upload date filter for video results.",
				"routing": {
					"send": {
						"type": "query",
						"property": "datePosted"
					}
				}
			},
			{
				"displayName": "Sort By",
				"name": "sortBy",
				"type": "options",
				"options": [
					{
						"name": "Relevance",
						"value": "relevance"
					},
					{
						"name": "Most Liked",
						"value": "most-liked"
					},
					{
						"name": "Date Posted",
						"value": "date-posted"
					}
				],
				"default": "relevance",
				"description": "Optional sort order for search results.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sortBy"
					}
				}
			},
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional two-letter ISO 3166-1 country code for localized search results.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, returns a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.search.hashtag.list"
				]
			}
		}
	},
	{
		"displayName": "Hashtag",
		"name": "hashtag",
		"type": "string",
		"default": "",
		"description": "Hashtag to search for. A leading # is optional.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "hashtag"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.search.hashtag.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.search.hashtag.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional ISO 3166-1 country code for the request. This sets the proxy region and does not filter results to that country only.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "Whether to request a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the video or photo post.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional ISO 3166-1 country code used to route the request when needed.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, returns a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			},
			{
				"displayName": "Download Media",
				"name": "downloadMedia",
				"type": "boolean",
				"default": false,
				"description": "When true, includes hosted CDN URLs in `downloads` when available. Adds 10 credits (11 total with the base lookup) on successful lookups, even if `downloads` is empty.",
				"routing": {
					"send": {
						"type": "query",
						"property": "downloadMedia"
					}
				}
			},
			{
				"displayName": "Get Transcript",
				"name": "getTranscript",
				"type": "boolean",
				"default": false,
				"description": "When true, includes the video transcript (WEBVTT) in `transcript` when one is available.",
				"routing": {
					"send": {
						"type": "query",
						"property": "getTranscript"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.comments.list"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the TikTok video whose comments should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.comments.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.comments.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, returns a smaller response with fewer fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.comments.replies.list"
				]
			}
		}
	},
	{
		"displayName": "Comment ID",
		"name": "commentId",
		"type": "string",
		"default": "",
		"description": "Parent comment id from List TikTok video comments (`data.comments[].id`).",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "commentId"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.comments.replies.list"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the TikTok video that contains the parent comment.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.comments.replies.list"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the TikTok video whose transcript should be returned.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.transcript.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.video.transcript.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Language",
				"name": "language",
				"type": "string",
				"default": "",
				"description": "Optional two-letter language code to request a transcript in a specific language when available.",
				"routing": {
					"send": {
						"type": "query",
						"property": "language"
					}
				}
			},
			{
				"displayName": "Use AI Fallback",
				"name": "useAiFallback",
				"type": "boolean",
				"default": false,
				"description": "When true, uses Social Fetch's AI fallback when a transcript is not otherwise available. Adds 10 credits on completed lookups (11 total with the base lookup).",
				"routing": {
					"send": {
						"type": "query",
						"property": "useAiFallback"
					}
				}
			}
		]
	},
	{
		"displayName": "Region",
		"name": "region",
		"type": "string",
		"default": "",
		"description": "Two-letter ISO 3166-1 country code for the request.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "region"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.feed.trending.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.feed.trending.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "When true, requests a smaller response with fewer optional fields.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "ID",
		"name": "id",
		"type": "string",
		"default": "",
		"description": "TikTok song or sound id. Use the trailing id from a music page URL, or `music.id` from a video lookup.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "id"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.song.get"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.music.videos.list"
				]
			}
		}
	},
	{
		"displayName": "Clip ID",
		"name": "clipId",
		"type": "string",
		"default": "",
		"description": "TikTok music clip id whose videos should be listed.",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.music.videos.list"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for TikTok Shop products.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.shop.products.search"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.shop.products.search"
				]
			}
		},
		"options": [
			{
				"displayName": "Page",
				"name": "page",
				"type": "number",
				"default": 0,
				"description": "1-based results page number. Omit to request the first page. Pagination is page-based.",
				"routing": {
					"send": {
						"type": "query",
						"property": "page"
					}
				}
			},
			{
				"displayName": "Region",
				"name": "region",
				"type": "options",
				"options": [
					{
						"name": "US",
						"value": "US"
					},
					{
						"name": "GB",
						"value": "GB"
					},
					{
						"name": "DE",
						"value": "DE"
					},
					{
						"name": "FR",
						"value": "FR"
					},
					{
						"name": "IT",
						"value": "IT"
					},
					{
						"name": "ID",
						"value": "ID"
					},
					{
						"name": "MY",
						"value": "MY"
					},
					{
						"name": "MX",
						"value": "MX"
					},
					{
						"name": "PH",
						"value": "PH"
					},
					{
						"name": "SG",
						"value": "SG"
					},
					{
						"name": "ES",
						"value": "ES"
					},
					{
						"name": "TH",
						"value": "TH"
					},
					{
						"name": "VN",
						"value": "VN"
					},
					{
						"name": "BR",
						"value": "BR"
					},
					{
						"name": "JP",
						"value": "JP"
					},
					{
						"name": "IE",
						"value": "IE"
					}
				],
				"default": "US",
				"description": "Optional country or region code for the product search catalog.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.shop.products.list"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public TikTok Shop store URL whose products should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.shop.products.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.shop.products.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "options",
				"options": [
					{
						"name": "US",
						"value": "US"
					},
					{
						"name": "GB",
						"value": "GB"
					},
					{
						"name": "DE",
						"value": "DE"
					},
					{
						"name": "FR",
						"value": "FR"
					},
					{
						"name": "IT",
						"value": "IT"
					},
					{
						"name": "ID",
						"value": "ID"
					},
					{
						"name": "MY",
						"value": "MY"
					},
					{
						"name": "MX",
						"value": "MX"
					},
					{
						"name": "PH",
						"value": "PH"
					},
					{
						"name": "SG",
						"value": "SG"
					},
					{
						"name": "ES",
						"value": "ES"
					},
					{
						"name": "TH",
						"value": "TH"
					},
					{
						"name": "VN",
						"value": "VN"
					},
					{
						"name": "BR",
						"value": "BR"
					},
					{
						"name": "JP",
						"value": "JP"
					},
					{
						"name": "IE",
						"value": "IE"
					}
				],
				"default": "US",
				"description": "Optional region code for the shop catalog. When omitted, the default catalog region is US.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public TikTok Shop product detail page URL for the product to retrieve.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.product.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.product.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "options",
				"options": [
					{
						"name": "US",
						"value": "US"
					},
					{
						"name": "GB",
						"value": "GB"
					},
					{
						"name": "DE",
						"value": "DE"
					},
					{
						"name": "FR",
						"value": "FR"
					},
					{
						"name": "IT",
						"value": "IT"
					},
					{
						"name": "ID",
						"value": "ID"
					},
					{
						"name": "MY",
						"value": "MY"
					},
					{
						"name": "MX",
						"value": "MX"
					},
					{
						"name": "PH",
						"value": "PH"
					},
					{
						"name": "SG",
						"value": "SG"
					},
					{
						"name": "ES",
						"value": "ES"
					},
					{
						"name": "TH",
						"value": "TH"
					},
					{
						"name": "VN",
						"value": "VN"
					},
					{
						"name": "BR",
						"value": "BR"
					},
					{
						"name": "JP",
						"value": "JP"
					},
					{
						"name": "IE",
						"value": "IE"
					}
				],
				"default": "US",
				"description": "Optional country or region code for the product catalog. When omitted, the default catalog region applies.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.product.reviews.list"
				]
			}
		},
		"options": [
			{
				"displayName": "URL",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Public TikTok Shop product detail page URL for the product whose reviews should be listed.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			},
			{
				"displayName": "Product ID",
				"name": "productId",
				"type": "string",
				"default": "",
				"description": "TikTok Shop product identifier. Provide this instead of `url` when you already know the product id.",
				"routing": {
					"send": {
						"type": "query",
						"property": "productId"
					}
				}
			},
			{
				"displayName": "Region",
				"name": "region",
				"type": "options",
				"options": [
					{
						"name": "US",
						"value": "US"
					},
					{
						"name": "GB",
						"value": "GB"
					},
					{
						"name": "DE",
						"value": "DE"
					},
					{
						"name": "FR",
						"value": "FR"
					},
					{
						"name": "IT",
						"value": "IT"
					},
					{
						"name": "ID",
						"value": "ID"
					},
					{
						"name": "MY",
						"value": "MY"
					},
					{
						"name": "MX",
						"value": "MX"
					},
					{
						"name": "PH",
						"value": "PH"
					},
					{
						"name": "SG",
						"value": "SG"
					},
					{
						"name": "ES",
						"value": "ES"
					},
					{
						"name": "TH",
						"value": "TH"
					},
					{
						"name": "VN",
						"value": "VN"
					},
					{
						"name": "BR",
						"value": "BR"
					},
					{
						"name": "JP",
						"value": "JP"
					},
					{
						"name": "IE",
						"value": "IE"
					}
				],
				"default": "US",
				"description": "Optional country or region code for the product review catalog. When omitted, the default catalog region applies.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Page",
				"name": "page",
				"type": "number",
				"default": 0,
				"description": "1-based review page number. Omit to request the first page.",
				"routing": {
					"send": {
						"type": "query",
						"property": "page"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.showcaseProducts.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "TikTok handle whose profile showcase products should be listed.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.showcaseProducts.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.profile.showcaseProducts.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional ISO 3166-1 country code for the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.adLibrary.ad.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Ad ID",
				"name": "adId",
				"type": "string",
				"default": "",
				"description": "TikTok Ad Library or Top Ads ad id.",
				"routing": {
					"send": {
						"type": "query",
						"property": "adId"
					}
				}
			},
			{
				"displayName": "URL",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Public TikTok Ad Library or Top Ads detail URL for the ad.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.adLibrary.ads.search.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"tiktok"
				],
				"operation": [
					"tiktok.adLibrary.ads.search.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Region",
				"name": "region",
				"type": "options",
				"options": [
					{
						"name": "DZ",
						"value": "DZ"
					},
					{
						"name": "AR",
						"value": "AR"
					},
					{
						"name": "AU",
						"value": "AU"
					},
					{
						"name": "AT",
						"value": "AT"
					},
					{
						"name": "AZ",
						"value": "AZ"
					},
					{
						"name": "BH",
						"value": "BH"
					},
					{
						"name": "BD",
						"value": "BD"
					},
					{
						"name": "BY",
						"value": "BY"
					},
					{
						"name": "BE",
						"value": "BE"
					},
					{
						"name": "BO",
						"value": "BO"
					},
					{
						"name": "BR",
						"value": "BR"
					},
					{
						"name": "BG",
						"value": "BG"
					},
					{
						"name": "KH",
						"value": "KH"
					},
					{
						"name": "CA",
						"value": "CA"
					},
					{
						"name": "CL",
						"value": "CL"
					},
					{
						"name": "CO",
						"value": "CO"
					},
					{
						"name": "CR",
						"value": "CR"
					},
					{
						"name": "HR",
						"value": "HR"
					},
					{
						"name": "CY",
						"value": "CY"
					},
					{
						"name": "CZ",
						"value": "CZ"
					},
					{
						"name": "DK",
						"value": "DK"
					},
					{
						"name": "DO",
						"value": "DO"
					},
					{
						"name": "EC",
						"value": "EC"
					},
					{
						"name": "EG",
						"value": "EG"
					},
					{
						"name": "EE",
						"value": "EE"
					},
					{
						"name": "FI",
						"value": "FI"
					},
					{
						"name": "FR",
						"value": "FR"
					},
					{
						"name": "DE",
						"value": "DE"
					},
					{
						"name": "GR",
						"value": "GR"
					},
					{
						"name": "GT",
						"value": "GT"
					},
					{
						"name": "JO",
						"value": "JO"
					},
					{
						"name": "HU",
						"value": "HU"
					},
					{
						"name": "ID",
						"value": "ID"
					},
					{
						"name": "IQ",
						"value": "IQ"
					},
					{
						"name": "IE",
						"value": "IE"
					},
					{
						"name": "IL",
						"value": "IL"
					},
					{
						"name": "IT",
						"value": "IT"
					},
					{
						"name": "JP",
						"value": "JP"
					},
					{
						"name": "KZ",
						"value": "KZ"
					},
					{
						"name": "KE",
						"value": "KE"
					},
					{
						"name": "KW",
						"value": "KW"
					},
					{
						"name": "LV",
						"value": "LV"
					},
					{
						"name": "LB",
						"value": "LB"
					},
					{
						"name": "MY",
						"value": "MY"
					},
					{
						"name": "MX",
						"value": "MX"
					},
					{
						"name": "MA",
						"value": "MA"
					},
					{
						"name": "NL",
						"value": "NL"
					},
					{
						"name": "NZ",
						"value": "NZ"
					},
					{
						"name": "NG",
						"value": "NG"
					},
					{
						"name": "NO",
						"value": "NO"
					},
					{
						"name": "OM",
						"value": "OM"
					},
					{
						"name": "PK",
						"value": "PK"
					},
					{
						"name": "PA",
						"value": "PA"
					},
					{
						"name": "PY",
						"value": "PY"
					},
					{
						"name": "PE",
						"value": "PE"
					},
					{
						"name": "PH",
						"value": "PH"
					},
					{
						"name": "PL",
						"value": "PL"
					},
					{
						"name": "PT",
						"value": "PT"
					},
					{
						"name": "PR",
						"value": "PR"
					},
					{
						"name": "QA",
						"value": "QA"
					},
					{
						"name": "LT",
						"value": "LT"
					},
					{
						"name": "RO",
						"value": "RO"
					},
					{
						"name": "SA",
						"value": "SA"
					},
					{
						"name": "RS",
						"value": "RS"
					},
					{
						"name": "SG",
						"value": "SG"
					},
					{
						"name": "SK",
						"value": "SK"
					},
					{
						"name": "SI",
						"value": "SI"
					},
					{
						"name": "ZA",
						"value": "ZA"
					},
					{
						"name": "KR",
						"value": "KR"
					},
					{
						"name": "ES",
						"value": "ES"
					},
					{
						"name": "LK",
						"value": "LK"
					},
					{
						"name": "SE",
						"value": "SE"
					},
					{
						"name": "CH",
						"value": "CH"
					},
					{
						"name": "TW",
						"value": "TW"
					},
					{
						"name": "TH",
						"value": "TH"
					},
					{
						"name": "TR",
						"value": "TR"
					},
					{
						"name": "AE",
						"value": "AE"
					},
					{
						"name": "GB",
						"value": "GB"
					},
					{
						"name": "US",
						"value": "US"
					},
					{
						"name": "UY",
						"value": "UY"
					},
					{
						"name": "VN",
						"value": "VN"
					}
				],
				"default": "DZ",
				"description": "Country code for Top Ads results. Default: `US`.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Period",
				"name": "period",
				"type": "options",
				"options": [
					{
						"name": "7",
						"value": "7"
					},
					{
						"name": "30",
						"value": "30"
					},
					{
						"name": "180",
						"value": "180"
					}
				],
				"default": "7",
				"description": "Time window in days for Top Ads.",
				"routing": {
					"send": {
						"type": "query",
						"property": "period"
					}
				}
			},
			{
				"displayName": "Query",
				"name": "query",
				"type": "string",
				"default": "",
				"description": "Optional keyword to search ad titles and content.",
				"placeholder": "e.g. automation",
				"routing": {
					"send": {
						"type": "query",
						"property": "query"
					}
				}
			},
			{
				"displayName": "Advertiser Name",
				"name": "advertiserName",
				"type": "string",
				"default": "",
				"description": "Search the public TikTok Ads Library by advertiser name. When set, results come from the public Ads Library instead of Top Ads.",
				"routing": {
					"send": {
						"type": "query",
						"property": "advertiserName"
					}
				}
			},
			{
				"displayName": "Order By",
				"name": "orderBy",
				"type": "options",
				"options": [
					{
						"name": "For You",
						"value": "for-you"
					},
					{
						"name": "Impression",
						"value": "impression"
					},
					{
						"name": "Play 2s Rate",
						"value": "play-2s-rate"
					},
					{
						"name": "Play 6s Rate",
						"value": "play-6s-rate"
					},
					{
						"name": "Cvr",
						"value": "cvr"
					},
					{
						"name": "Ctr",
						"value": "ctr"
					},
					{
						"name": "Like",
						"value": "like"
					}
				],
				"default": "for-you",
				"description": "Sort metric for Top Ads. Default: `for-you`.",
				"routing": {
					"send": {
						"type": "query",
						"property": "orderBy"
					}
				}
			},
			{
				"displayName": "Industry",
				"name": "industry",
				"type": "options",
				"options": [
					{
						"name": "Apparel Accessories",
						"value": "apparel-accessories"
					},
					{
						"name": "Appliances",
						"value": "appliances"
					},
					{
						"name": "Apps",
						"value": "apps"
					},
					{
						"name": "Baby Kids Maternity",
						"value": "baby-kids-maternity"
					},
					{
						"name": "Beauty Personal Care",
						"value": "beauty-personal-care"
					},
					{
						"name": "Business Services",
						"value": "business-services"
					},
					{
						"name": "Ecommerce Non App",
						"value": "ecommerce-non-app"
					},
					{
						"name": "Education",
						"value": "education"
					},
					{
						"name": "Financial Services",
						"value": "financial-services"
					},
					{
						"name": "Food Beverage",
						"value": "food-beverage"
					},
					{
						"name": "Games",
						"value": "games"
					},
					{
						"name": "Health",
						"value": "health"
					},
					{
						"name": "Home Improvement",
						"value": "home-improvement"
					},
					{
						"name": "Household Products",
						"value": "household-products"
					},
					{
						"name": "Life Services",
						"value": "life-services"
					},
					{
						"name": "News Entertainment",
						"value": "news-entertainment"
					},
					{
						"name": "Pets",
						"value": "pets"
					},
					{
						"name": "Sports Outdoor",
						"value": "sports-outdoor"
					},
					{
						"name": "Tech Electronics",
						"value": "tech-electronics"
					},
					{
						"name": "Travel",
						"value": "travel"
					},
					{
						"name": "Vehicle Transportation",
						"value": "vehicle-transportation"
					}
				],
				"default": "apparel-accessories",
				"description": "Industry filter for Top Ads.",
				"routing": {
					"send": {
						"type": "query",
						"property": "industry"
					}
				}
			},
			{
				"displayName": "Objective",
				"name": "objective",
				"type": "options",
				"options": [
					{
						"name": "App Installs",
						"value": "app-installs"
					},
					{
						"name": "Conversions",
						"value": "conversions"
					},
					{
						"name": "Lead Generation",
						"value": "lead-generation"
					},
					{
						"name": "Product Sales",
						"value": "product-sales"
					},
					{
						"name": "Reach",
						"value": "reach"
					},
					{
						"name": "Traffic",
						"value": "traffic"
					},
					{
						"name": "Video Views",
						"value": "video-views"
					}
				],
				"default": "app-installs",
				"description": "Campaign objective filter for Top Ads.",
				"routing": {
					"send": {
						"type": "query",
						"property": "objective"
					}
				}
			},
			{
				"displayName": "Duration",
				"name": "duration",
				"type": "options",
				"options": [
					{
						"name": "Under 10s",
						"value": "under-10s"
					},
					{
						"name": "10 20s",
						"value": "10-20s"
					},
					{
						"name": "20 30s",
						"value": "20-30s"
					},
					{
						"name": "30 40s",
						"value": "30-40s"
					},
					{
						"name": "40 50s",
						"value": "40-50s"
					},
					{
						"name": "Over 50s",
						"value": "over-50s"
					}
				],
				"default": "under-10s",
				"description": "Video duration filter for Top Ads.",
				"routing": {
					"send": {
						"type": "query",
						"property": "duration"
					}
				}
			},
			{
				"displayName": "Likes",
				"name": "likes",
				"type": "options",
				"options": [
					{
						"name": "Top 1 20",
						"value": "top-1-20"
					},
					{
						"name": "Top 21 40",
						"value": "top-21-40"
					},
					{
						"name": "Top 41 60",
						"value": "top-41-60"
					},
					{
						"name": "Top 61 80",
						"value": "top-61-80"
					},
					{
						"name": "Top 81 100",
						"value": "top-81-100"
					}
				],
				"default": "top-1-20",
				"description": "Likes percentile filter for Top Ads.",
				"routing": {
					"send": {
						"type": "query",
						"property": "likes"
					}
				}
			},
			{
				"displayName": "Ad Format",
				"name": "adFormat",
				"type": "options",
				"options": [
					{
						"name": "Spark Ads",
						"value": "spark-ads"
					},
					{
						"name": "Non Spark Ads",
						"value": "non-spark-ads"
					}
				],
				"default": "spark-ads",
				"description": "Ad format filter for Top Ads.",
				"routing": {
					"send": {
						"type": "query",
						"property": "adFormat"
					}
				}
			},
			{
				"displayName": "Ad Language",
				"name": "adLanguage",
				"type": "options",
				"options": [
					{
						"name": "En",
						"value": "en"
					},
					{
						"name": "Es",
						"value": "es"
					},
					{
						"name": "Ar",
						"value": "ar"
					},
					{
						"name": "Vi",
						"value": "vi"
					},
					{
						"name": "Th",
						"value": "th"
					},
					{
						"name": "De",
						"value": "de"
					},
					{
						"name": "ID",
						"value": "id"
					},
					{
						"name": "Pt",
						"value": "pt"
					},
					{
						"name": "Fr",
						"value": "fr"
					},
					{
						"name": "Ms",
						"value": "ms"
					},
					{
						"name": "Nl",
						"value": "nl"
					},
					{
						"name": "Ja",
						"value": "ja"
					},
					{
						"name": "It",
						"value": "it"
					},
					{
						"name": "Ro",
						"value": "ro"
					},
					{
						"name": "Zh Hant",
						"value": "zh-Hant"
					},
					{
						"name": "Ko",
						"value": "ko"
					}
				],
				"default": "en",
				"description": "Ad language filter for Top Ads.",
				"routing": {
					"send": {
						"type": "query",
						"property": "adLanguage"
					}
				}
			}
		]
	}
];
