// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { cursorPagination } from "../shared/pagination";

export const truthsocial: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"truthsocial"
				]
			}
		},
		"default": "truthsocial.profile.get",
		"options": [
			{
				"name": "Profile",
				"value": "truthsocial.profile.get",
				"action": "Get Truth Social profile",
				"description": "Get a Truth Social profile by handle or account id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/truthsocial/profiles/{{$parameter[\"handle\"]}}"
					}
				}
			},
			{
				"name": "Profile Posts",
				"value": "truthsocial.profile.posts.list",
				"action": "List Truth Social profile posts",
				"description": "List posts from a Truth Social profile by handle or account id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/truthsocial/profiles/{{$parameter[\"handle\"]}}/posts"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Post",
				"value": "truthsocial.post.get",
				"action": "Get Truth Social post",
				"description": "Get a Truth Social post by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/truthsocial/posts"
					}
				}
			}
		]
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "Truth Social handle or account id.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"truthsocial"
				],
				"operation": [
					"truthsocial.profile.get"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"truthsocial"
				],
				"operation": [
					"truthsocial.profile.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "Truth Social handle or account id.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"truthsocial"
				],
				"operation": [
					"truthsocial.profile.posts.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"truthsocial"
				],
				"operation": [
					"truthsocial.profile.posts.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Include Replies",
				"name": "includeReplies",
				"type": "boolean",
				"default": false,
				"description": "When true, includes reply posts in the timeline. Adds 2 credits (4 total including the base lookup). Default: false (top-level posts only).",
				"routing": {
					"send": {
						"type": "query",
						"property": "includeReplies"
					}
				}
			},
			{
				"displayName": "Limit",
				"name": "limit",
				"type": "number",
				"default": 20,
				"description": "Maximum posts to return (1–20). Default: 20.",
				"routing": {
					"send": {
						"type": "query",
						"property": "limit"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the Truth Social post.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"truthsocial"
				],
				"operation": [
					"truthsocial.post.get"
				]
			}
		}
	}
];
