// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { cursorPagination } from "../shared/pagination";

export const twitter: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				]
			}
		},
		"default": "twitter.profile.get",
		"options": [
			{
				"name": "Profile",
				"value": "twitter.profile.get",
				"action": "Get Twitter profile",
				"description": "Get an X (Twitter) profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/twitter/profiles/{{$parameter[\"handle\"]}}"
					}
				}
			},
			{
				"name": "Profile Tweets",
				"value": "twitter.profile.tweets.list",
				"action": "List Twitter profile tweets",
				"description": "List tweets from an X profile by handle.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "=/v1/twitter/profiles/{{$parameter[\"handle\"]}}/tweets"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Tweet",
				"value": "twitter.tweet.get",
				"action": "Get Twitter tweet",
				"description": "Get a single tweet by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/twitter/tweets"
					}
				}
			},
			{
				"name": "Tweet Replies",
				"value": "twitter.tweet.replies.list",
				"action": "List Twitter tweet replies",
				"description": "List replies to a tweet by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/twitter/tweets/replies"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Transcript",
				"value": "twitter.tweet.transcript.get",
				"action": "Get Twitter tweet transcript",
				"description": "Get the transcript for a video tweet by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/twitter/tweets/transcript"
					}
				}
			},
			{
				"name": "Search",
				"value": "twitter.search.list",
				"action": "Search Twitter posts",
				"description": "Search X posts by keyword.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/twitter/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Hashtag Search",
				"value": "twitter.hashtag.list",
				"action": "Search Twitter by hashtag",
				"description": "Search X posts by hashtag (not free-text keyword — use twitter.search.list for that).",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/twitter/hashtags"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Community",
				"value": "twitter.community.get",
				"action": "Get Twitter community",
				"description": "Get details for an X community by community id or URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/twitter/communities"
					}
				}
			},
			{
				"name": "Community Tweets",
				"value": "twitter.community.tweets.list",
				"action": "List Twitter community tweets",
				"description": "List tweets from an X community by community id or URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/twitter/communities/tweets"
					}
				}
			}
		]
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "X handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.profile.get"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.profile.tweets.list"
				]
			}
		}
	},
	{
		"displayName": "Handle",
		"name": "handle",
		"type": "string",
		"default": "",
		"description": "X handle to look up, with or without a leading @.",
		"placeholder": "e.g. n8n",
		"required": true,
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.profile.tweets.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.profile.tweets.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Limit",
				"name": "limit",
				"type": "number",
				"default": 40,
				"description": "Optional page size. Defaults to 40 when omitted. Maximum supported value is 100.",
				"routing": {
					"send": {
						"type": "query",
						"property": "limit"
					}
				}
			},
			{
				"displayName": "Include Replies",
				"name": "includeReplies",
				"type": "boolean",
				"default": false,
				"description": "Optional: include reply tweets in the returned list. Defaults to false.",
				"routing": {
					"send": {
						"type": "query",
						"property": "includeReplies"
					}
				}
			},
			{
				"displayName": "Include Pinned",
				"name": "includePinned",
				"type": "boolean",
				"default": false,
				"description": "Optional: include pinned tweets on the first page. Defaults to false.",
				"routing": {
					"send": {
						"type": "query",
						"property": "includePinned"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Tweet permalink or identifier.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.tweet.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.tweet.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Trim",
				"name": "trim",
				"type": "boolean",
				"default": false,
				"description": "Optional: omit author profile and tweet `core` for a smaller response.",
				"routing": {
					"send": {
						"type": "query",
						"property": "trim"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.tweet.replies.list"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Tweet permalink or identifier.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.tweet.replies.list"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Tweet permalink or identifier.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.tweet.transcript.get"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.search.list"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text to run against public posts on X.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.search.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.search.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Section",
				"name": "section",
				"type": "options",
				"options": [
					{
						"name": "Top",
						"value": "top"
					},
					{
						"name": "Latest",
						"value": "latest"
					},
					{
						"name": "People",
						"value": "people"
					},
					{
						"name": "Photos",
						"value": "photos"
					},
					{
						"name": "Videos",
						"value": "videos"
					}
				],
				"default": "top",
				"description": "Optional search section filter. Omit to use the default `top` section.",
				"routing": {
					"send": {
						"type": "query",
						"property": "section"
					}
				}
			},
			{
				"displayName": "Min Retweets",
				"name": "minRetweets",
				"type": "number",
				"default": 0,
				"description": "Optional minimum retweet count filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "minRetweets"
					}
				}
			},
			{
				"displayName": "Min Likes",
				"name": "minLikes",
				"type": "number",
				"default": 0,
				"description": "Optional minimum like count filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "minLikes"
					}
				}
			},
			{
				"displayName": "Min Replies",
				"name": "minReplies",
				"type": "number",
				"default": 0,
				"description": "Optional minimum reply count filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "minReplies"
					}
				}
			},
			{
				"displayName": "Limit",
				"name": "limit",
				"type": "number",
				"default": 0,
				"description": "Optional page size. Maximum supported value is 20.",
				"routing": {
					"send": {
						"type": "query",
						"property": "limit"
					}
				}
			},
			{
				"displayName": "Start Date",
				"name": "startDate",
				"type": "string",
				"default": "",
				"description": "Optional start date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "startDate"
					}
				}
			},
			{
				"displayName": "End Date",
				"name": "endDate",
				"type": "string",
				"default": "",
				"description": "Optional end date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "endDate"
					}
				}
			},
			{
				"displayName": "Language",
				"name": "language",
				"type": "options",
				"options": [
					{
						"name": "En",
						"value": "en"
					},
					{
						"name": "Es",
						"value": "es"
					},
					{
						"name": "Fr",
						"value": "fr"
					},
					{
						"name": "De",
						"value": "de"
					},
					{
						"name": "It",
						"value": "it"
					},
					{
						"name": "Pt",
						"value": "pt"
					},
					{
						"name": "Ru",
						"value": "ru"
					},
					{
						"name": "Zh",
						"value": "zh"
					},
					{
						"name": "Ja",
						"value": "ja"
					},
					{
						"name": "Ko",
						"value": "ko"
					},
					{
						"name": "Ar",
						"value": "ar"
					},
					{
						"name": "Bg",
						"value": "bg"
					},
					{
						"name": "Hr",
						"value": "hr"
					},
					{
						"name": "Cs",
						"value": "cs"
					},
					{
						"name": "Da",
						"value": "da"
					},
					{
						"name": "Nl",
						"value": "nl"
					},
					{
						"name": "Et",
						"value": "et"
					},
					{
						"name": "Fi",
						"value": "fi"
					},
					{
						"name": "El",
						"value": "el"
					},
					{
						"name": "Hu",
						"value": "hu"
					},
					{
						"name": "ID",
						"value": "id"
					},
					{
						"name": "Ga",
						"value": "ga"
					},
					{
						"name": "Lv",
						"value": "lv"
					},
					{
						"name": "Lt",
						"value": "lt"
					},
					{
						"name": "No",
						"value": "no"
					},
					{
						"name": "Pl",
						"value": "pl"
					},
					{
						"name": "Ro",
						"value": "ro"
					},
					{
						"name": "Sk",
						"value": "sk"
					},
					{
						"name": "Sl",
						"value": "sl"
					},
					{
						"name": "Sv",
						"value": "sv"
					},
					{
						"name": "Tr",
						"value": "tr"
					},
					{
						"name": "Uk",
						"value": "uk"
					},
					{
						"name": "Vi",
						"value": "vi"
					},
					{
						"name": "Cy",
						"value": "cy"
					},
					{
						"name": "Zu",
						"value": "zu"
					}
				],
				"default": "en",
				"description": "Optional language filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "language"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.hashtag.list"
				]
			}
		}
	},
	{
		"displayName": "Hashtag",
		"name": "hashtag",
		"type": "string",
		"default": "",
		"description": "Hashtag to search for.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "hashtag"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.hashtag.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.hashtag.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Section",
				"name": "section",
				"type": "options",
				"options": [
					{
						"name": "Top",
						"value": "top"
					},
					{
						"name": "Latest",
						"value": "latest"
					},
					{
						"name": "People",
						"value": "people"
					},
					{
						"name": "Photos",
						"value": "photos"
					},
					{
						"name": "Videos",
						"value": "videos"
					}
				],
				"default": "top",
				"description": "Optional section filter for the hashtag feed. Omit to use the default `top` section.",
				"routing": {
					"send": {
						"type": "query",
						"property": "section"
					}
				}
			},
			{
				"displayName": "Limit",
				"name": "limit",
				"type": "number",
				"default": 0,
				"description": "Optional page size. Maximum supported value is 20.",
				"routing": {
					"send": {
						"type": "query",
						"property": "limit"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Community URL to look up.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.community.get"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Community URL to look up.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"twitter"
				],
				"operation": [
					"twitter.community.tweets.list"
				]
			}
		}
	}
];
