// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";

export const web: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				]
			}
		},
		"default": "web.search.run",
		"options": [
			{
				"name": "Search",
				"value": "web.search.run",
				"action": "Search the web",
				"description": "Search the public web and return ranked results with snippets.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/web/search"
					}
				}
			},
			{
				"name": "Markdown",
				"value": "web.markdown.generate",
				"action": "Generate web page markdown",
				"description": "Convert a web page into clean markdown.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/web/markdown"
					}
				}
			},
			{
				"name": "Ask",
				"value": "web.ask.run",
				"action": "Ask a question about a web page",
				"description": "Ask a natural-language question about a web page and get an LLM-generated answer.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/web/ask"
					}
				}
			},
			{
				"name": "HTML",
				"value": "web.html.generate",
				"action": "Generate web page HTML",
				"description": "Fetch and return cleaned HTML for a web page.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/web/html"
					}
				}
			},
			{
				"name": "Crawl",
				"value": "web.crawl.run",
				"action": "Crawl web pages",
				"description": "Crawl a small set of web pages synchronously.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/web/crawl"
					}
				}
			}
		]
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text to run against the public web.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.search.run"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.search.run"
				]
			}
		},
		"options": [
			{
				"displayName": "Search Depth",
				"name": "searchDepth",
				"type": "options",
				"options": [
					{
						"name": "Basic",
						"value": "basic"
					},
					{
						"name": "Fast",
						"value": "fast"
					},
					{
						"name": "Ultra Fast",
						"value": "ultra-fast"
					},
					{
						"name": "Advanced",
						"value": "advanced"
					}
				],
				"default": "basic",
				"description": "Search depth: basic (default), fast, ultra-fast, or advanced.",
				"routing": {
					"send": {
						"type": "query",
						"property": "searchDepth"
					}
				}
			},
			{
				"displayName": "Max Results",
				"name": "maxResults",
				"type": "number",
				"default": 0,
				"description": "Maximum number of search results to return (1–20).",
				"routing": {
					"send": {
						"type": "query",
						"property": "maxResults"
					}
				}
			},
			{
				"displayName": "Topic",
				"name": "topic",
				"type": "options",
				"options": [
					{
						"name": "General",
						"value": "general"
					},
					{
						"name": "News",
						"value": "news"
					},
					{
						"name": "Finance",
						"value": "finance"
					}
				],
				"default": "general",
				"description": "Search topic category. Defaults to general.",
				"routing": {
					"send": {
						"type": "query",
						"property": "topic"
					}
				}
			},
			{
				"displayName": "Time Range",
				"name": "timeRange",
				"type": "options",
				"options": [
					{
						"name": "Day",
						"value": "day"
					},
					{
						"name": "Week",
						"value": "week"
					},
					{
						"name": "Month",
						"value": "month"
					},
					{
						"name": "Year",
						"value": "year"
					}
				],
				"default": "day",
				"description": "Optional time range filter based on publish or last-updated date.",
				"routing": {
					"send": {
						"type": "query",
						"property": "timeRange"
					}
				}
			},
			{
				"displayName": "Start Date",
				"name": "startDate",
				"type": "string",
				"default": "",
				"description": "Optional start date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "startDate"
					}
				}
			},
			{
				"displayName": "End Date",
				"name": "endDate",
				"type": "string",
				"default": "",
				"description": "Optional end date filter in YYYY-MM-DD format.",
				"routing": {
					"send": {
						"type": "query",
						"property": "endDate"
					}
				}
			},
			{
				"displayName": "Include Domain",
				"name": "includeDomain",
				"type": "string",
				"typeOptions": {
					"multipleValues": true
				},
				"default": [],
				"description": "Domains to include in results. Repeat includeDomain for multiple values (max 20).",
				"routing": {
					"send": {
						"type": "query",
						"property": "includeDomain"
					}
				}
			},
			{
				"displayName": "Exclude Domain",
				"name": "excludeDomain",
				"type": "string",
				"typeOptions": {
					"multipleValues": true
				},
				"default": [],
				"description": "Domains to exclude from results. Repeat excludeDomain for multiple values (max 20).",
				"routing": {
					"send": {
						"type": "query",
						"property": "excludeDomain"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Web page URL to fetch.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.markdown.generate"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.markdown.generate"
				]
			}
		},
		"options": [
			{
				"displayName": "Filter",
				"name": "filter",
				"type": "options",
				"options": [
					{
						"name": "Fit",
						"value": "fit"
					},
					{
						"name": "Raw",
						"value": "raw"
					},
					{
						"name": "Bm25",
						"value": "bm25"
					}
				],
				"default": "fit",
				"description": "Content filter strategy for markdown extraction.",
				"routing": {
					"send": {
						"type": "query",
						"property": "filter"
					}
				}
			},
			{
				"displayName": "Query",
				"name": "query",
				"type": "string",
				"default": "",
				"description": "Optional query string used by the bm25 filter to rank relevant content.",
				"placeholder": "e.g. automation",
				"routing": {
					"send": {
						"type": "query",
						"property": "query"
					}
				}
			},
			{
				"displayName": "Cache Mode",
				"name": "cacheMode",
				"type": "options",
				"options": [
					{
						"name": "Enabled",
						"value": "enabled"
					},
					{
						"name": "Bypass",
						"value": "bypass"
					},
					{
						"name": "Write Only",
						"value": "write_only"
					}
				],
				"default": "enabled",
				"description": "Cache behavior. Defaults to enabled.",
				"routing": {
					"send": {
						"type": "query",
						"property": "cacheMode"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Web page URL to fetch.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.ask.run"
				]
			}
		}
	},
	{
		"displayName": "Q",
		"name": "q",
		"type": "string",
		"default": "",
		"description": "Natural-language question to answer about the page content.",
		"placeholder": "e.g. What is this page about?",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "q"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.ask.run"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Web page URL to fetch.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.html.generate"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"typeOptions": {
			"multipleValues": true
		},
		"default": [],
		"description": "URLs to crawl. Repeat the `url` query parameter for multiple pages (max 5).",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.crawl.run"
				]
			}
		}
	}
];
