// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";

export const web: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				]
			}
		},
		"default": "web.markdown.generate",
		"options": [
			{
				"name": "Markdown",
				"value": "web.markdown.generate",
				"action": "Generate web page markdown",
				"description": "Convert a web page into clean markdown.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/web/markdown"
					}
				}
			},
			{
				"name": "Ask",
				"value": "web.ask.run",
				"action": "Ask a question about a web page",
				"description": "Ask a natural-language question about a web page and get an LLM-generated answer.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/web/ask"
					}
				}
			},
			{
				"name": "HTML",
				"value": "web.html.generate",
				"action": "Generate web page HTML",
				"description": "Fetch and return cleaned HTML for a web page.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/web/html"
					}
				}
			},
			{
				"name": "Crawl",
				"value": "web.crawl.run",
				"action": "Crawl web pages",
				"description": "Crawl a small set of web pages synchronously.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/web/crawl"
					}
				}
			}
		]
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Absolute http or https URL to fetch.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.markdown.generate"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.markdown.generate"
				]
			}
		},
		"options": [
			{
				"displayName": "Filter",
				"name": "filter",
				"type": "options",
				"options": [
					{
						"name": "Fit",
						"value": "fit"
					},
					{
						"name": "Raw",
						"value": "raw"
					},
					{
						"name": "Bm25",
						"value": "bm25"
					}
				],
				"default": "fit",
				"description": "Content filter strategy for markdown extraction.",
				"routing": {
					"send": {
						"type": "query",
						"property": "filter"
					}
				}
			},
			{
				"displayName": "Query",
				"name": "query",
				"type": "string",
				"default": "",
				"description": "Optional query string used by the bm25 filter to rank relevant content.",
				"placeholder": "e.g. automation",
				"routing": {
					"send": {
						"type": "query",
						"property": "query"
					}
				}
			},
			{
				"displayName": "Cache Mode",
				"name": "cacheMode",
				"type": "options",
				"options": [
					{
						"name": "Enabled",
						"value": "enabled"
					},
					{
						"name": "Bypass",
						"value": "bypass"
					},
					{
						"name": "Write Only",
						"value": "write_only"
					}
				],
				"default": "enabled",
				"description": "Cache behavior: enabled (read/write cache), bypass (skip cache), or write_only.",
				"routing": {
					"send": {
						"type": "query",
						"property": "cacheMode"
					}
				}
			}
		]
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Absolute http or https URL to fetch.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.ask.run"
				]
			}
		}
	},
	{
		"displayName": "Q",
		"name": "q",
		"type": "string",
		"default": "",
		"description": "Natural-language question to answer about the page content.",
		"placeholder": "e.g. What is this page about?",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "q"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.ask.run"
				]
			}
		}
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Absolute http or https URL to fetch.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.html.generate"
				]
			}
		}
	},
	{
		"displayName": "Url",
		"name": "url",
		"type": "string",
		"typeOptions": {
			"multipleValues": true
		},
		"default": [],
		"description": "URLs to crawl. Repeat the `url` query parameter for multiple pages (max 5).",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"web"
				],
				"operation": [
					"web.crawl.run"
				]
			}
		}
	}
];
