// @generated by integrations/n8n/scripts/generate-from-openapi.mts — do not edit
import type { INodeProperties } from "n8n-workflow";
import { cursorPagination } from "../shared/pagination";

export const youtube: INodeProperties[] = [
	{
		"displayName": "Operation",
		"name": "operation",
		"type": "options",
		"noDataExpression": true,
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				]
			}
		},
		"default": "youtube.channel.get",
		"options": [
			{
				"name": "Channel",
				"value": "youtube.channel.get",
				"action": "Get YouTube channel",
				"description": "Get YouTube channel details by channel id, handle, or URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/youtube/channel"
					}
				}
			},
			{
				"name": "Channel Videos",
				"value": "youtube.channel.videos.list",
				"action": "List YouTube channel videos",
				"description": "List long-form videos from a YouTube channel (not Shorts — use youtube.channel.shorts.list).",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/youtube/channels/videos"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Channel Shorts",
				"value": "youtube.channel.shorts.list",
				"action": "List YouTube channel shorts",
				"description": "List Shorts from a YouTube channel (not long-form videos).",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/youtube/channels/shorts"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Playlist",
				"value": "youtube.playlist.get",
				"action": "Get YouTube playlist",
				"description": "Get a YouTube playlist by playlist id.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/youtube/playlists"
					}
				}
			},
			{
				"name": "Community Post",
				"value": "youtube.community.post.get",
				"action": "Get YouTube community post",
				"description": "Get a YouTube community post by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/youtube/community-posts"
					}
				}
			},
			{
				"name": "Search",
				"value": "youtube.search.list",
				"action": "Search YouTube",
				"description": "Search YouTube videos, channels, and playlists by keyword.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/youtube/search"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Hashtag Search",
				"value": "youtube.search.hashtag.list",
				"action": "Search YouTube by hashtag",
				"description": "Search YouTube content by hashtag.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/youtube/search/hashtags"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Trending Shorts",
				"value": "youtube.shorts.trending.list",
				"action": "List trending YouTube Shorts",
				"description": "List currently trending YouTube Shorts.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/youtube/shorts/trending"
					}
				}
			},
			{
				"name": "Video",
				"value": "youtube.video.get",
				"action": "Get YouTube video",
				"description": "Get a single YouTube video by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/youtube/videos"
					}
				}
			},
			{
				"name": "Comments",
				"value": "youtube.video.comments.list",
				"action": "List YouTube video comments",
				"description": "List comments on a YouTube video by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/youtube/videos/comments"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Replies",
				"value": "youtube.video.comments.replies.list",
				"action": "List YouTube comment replies",
				"description": "List replies to a YouTube comment.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/youtube/videos/comments/replies"
					},
					"send": {
						"paginate": "={{$parameter[\"returnAll\"]}}"
					},
					"operations": {
						"pagination": cursorPagination
					}
				}
			},
			{
				"name": "Transcript",
				"value": "youtube.video.transcript.get",
				"action": "Get YouTube video transcript",
				"description": "Get the transcript for a YouTube video by URL.",
				"routing": {
					"request": {
						"method": "GET",
						"url": "/v1/youtube/videos/transcript"
					}
				}
			}
		]
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.channel.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Channel ID",
				"name": "channelId",
				"type": "string",
				"default": "",
				"description": "Optional YouTube channel id for the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "channelId"
					}
				}
			},
			{
				"displayName": "Handle",
				"name": "handle",
				"type": "string",
				"default": "",
				"description": "Optional YouTube channel handle for the request.",
				"placeholder": "e.g. n8n",
				"routing": {
					"send": {
						"type": "query",
						"property": "handle"
					}
				}
			},
			{
				"displayName": "URL",
				"name": "url",
				"type": "string",
				"default": "",
				"description": "Optional YouTube channel URL for the request.",
				"placeholder": "e.g. https://example.com/page",
				"routing": {
					"send": {
						"type": "query",
						"property": "url"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.channel.videos.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.channel.videos.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Channel ID",
				"name": "channelId",
				"type": "string",
				"default": "",
				"description": "Optional YouTube channel id for the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "channelId"
					}
				}
			},
			{
				"displayName": "Handle",
				"name": "handle",
				"type": "string",
				"default": "",
				"description": "Optional YouTube channel handle for the request.",
				"placeholder": "e.g. n8n",
				"routing": {
					"send": {
						"type": "query",
						"property": "handle"
					}
				}
			},
			{
				"displayName": "Sort By",
				"name": "sortBy",
				"type": "options",
				"options": [
					{
						"name": "Latest",
						"value": "latest"
					},
					{
						"name": "Popular",
						"value": "popular"
					}
				],
				"default": "latest",
				"description": "Optional sort order for the returned YouTube videos.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sortBy"
					}
				}
			},
			{
				"displayName": "Include Extras",
				"name": "includeExtras",
				"type": "boolean",
				"default": false,
				"description": "Optional flag to include richer per-video metadata when available.",
				"routing": {
					"send": {
						"type": "query",
						"property": "includeExtras"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.channel.shorts.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.channel.shorts.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Channel ID",
				"name": "channelId",
				"type": "string",
				"default": "",
				"description": "Optional YouTube channel id for the request.",
				"routing": {
					"send": {
						"type": "query",
						"property": "channelId"
					}
				}
			},
			{
				"displayName": "Handle",
				"name": "handle",
				"type": "string",
				"default": "",
				"description": "Optional YouTube channel handle for the request.",
				"placeholder": "e.g. n8n",
				"routing": {
					"send": {
						"type": "query",
						"property": "handle"
					}
				}
			},
			{
				"displayName": "Sort By",
				"name": "sortBy",
				"type": "options",
				"options": [
					{
						"name": "Latest",
						"value": "latest"
					},
					{
						"name": "Popular",
						"value": "popular"
					}
				],
				"default": "latest",
				"description": "Optional sort order for the returned YouTube Shorts.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sortBy"
					}
				}
			}
		]
	},
	{
		"displayName": "Playlist ID",
		"name": "playlistId",
		"type": "string",
		"default": "",
		"description": "YouTube playlist id, or a YouTube playlist URL (the `list` query value is used when present).",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "playlistId"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.playlist.get"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Public YouTube community post URL.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.community.post.get"
				]
			}
		}
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.search.list"
				]
			}
		}
	},
	{
		"displayName": "Query",
		"name": "query",
		"type": "string",
		"default": "",
		"description": "Search query text for YouTube content.",
		"placeholder": "e.g. automation",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "query"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.search.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.search.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Upload Date",
				"name": "uploadDate",
				"type": "options",
				"options": [
					{
						"name": "Today",
						"value": "today"
					},
					{
						"name": "This Week",
						"value": "this_week"
					},
					{
						"name": "This Month",
						"value": "this_month"
					},
					{
						"name": "This Year",
						"value": "this_year"
					}
				],
				"default": "today",
				"description": "Optional upload date filter for video results.",
				"routing": {
					"send": {
						"type": "query",
						"property": "uploadDate"
					}
				}
			},
			{
				"displayName": "Sort By",
				"name": "sortBy",
				"type": "options",
				"options": [
					{
						"name": "Relevance",
						"value": "relevance"
					},
					{
						"name": "Popular",
						"value": "popular"
					}
				],
				"default": "relevance",
				"description": "Optional sort order for search results.",
				"routing": {
					"send": {
						"type": "query",
						"property": "sortBy"
					}
				}
			},
			{
				"displayName": "Type",
				"name": "type",
				"type": "options",
				"options": [
					{
						"name": "Videos",
						"value": "videos"
					},
					{
						"name": "Shorts",
						"value": "shorts"
					},
					{
						"name": "Channels",
						"value": "channels"
					},
					{
						"name": "Playlists",
						"value": "playlists"
					}
				],
				"default": "videos",
				"description": "Optional content type filter for search results.",
				"routing": {
					"send": {
						"type": "query",
						"property": "type"
					}
				}
			},
			{
				"displayName": "Duration",
				"name": "duration",
				"type": "options",
				"options": [
					{
						"name": "Under 3 Min",
						"value": "under_3_min"
					},
					{
						"name": "Between 3 and 20 Min",
						"value": "between_3_and_20_min"
					},
					{
						"name": "Over 20 Min",
						"value": "over_20_min"
					}
				],
				"default": "under_3_min",
				"description": "Optional duration filter for video results. Applies to videos, not shorts.",
				"routing": {
					"send": {
						"type": "query",
						"property": "duration"
					}
				}
			},
			{
				"displayName": "Region",
				"name": "region",
				"type": "string",
				"default": "",
				"description": "Optional ISO 3166-1 country code for localized search results.",
				"routing": {
					"send": {
						"type": "query",
						"property": "region"
					}
				}
			},
			{
				"displayName": "Include Extras",
				"name": "includeExtras",
				"type": "boolean",
				"default": false,
				"description": "When true, returns richer per-video metadata when available. May increase response time.",
				"routing": {
					"send": {
						"type": "query",
						"property": "includeExtras"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.search.hashtag.list"
				]
			}
		}
	},
	{
		"displayName": "Hashtag",
		"name": "hashtag",
		"type": "string",
		"default": "",
		"description": "Hashtag to search for. A leading # is optional.",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "hashtag"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.search.hashtag.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.search.hashtag.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Type",
				"name": "type",
				"type": "options",
				"options": [
					{
						"name": "All",
						"value": "all"
					},
					{
						"name": "Shorts",
						"value": "shorts"
					}
				],
				"default": "all",
				"description": "Optional content filter.",
				"routing": {
					"send": {
						"type": "query",
						"property": "type"
					}
				}
			}
		]
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the YouTube video. Shorts URLs are also supported.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.video.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.video.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Language",
				"name": "language",
				"type": "string",
				"default": "",
				"description": "Optional preferred language for returned text when the source supports localization.",
				"routing": {
					"send": {
						"type": "query",
						"property": "language"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.video.comments.list"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the YouTube video whose comments should be listed.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.video.comments.list"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.video.comments.list"
				]
			}
		},
		"options": [
			{
				"displayName": "Order",
				"name": "order",
				"type": "options",
				"options": [
					{
						"name": "Top",
						"value": "top"
					},
					{
						"name": "Newest",
						"value": "newest"
					}
				],
				"default": "top",
				"description": "Comment sort order. `top` returns highest-ranked comments; `newest` returns the most recent comments.",
				"routing": {
					"send": {
						"type": "query",
						"property": "order"
					}
				}
			}
		]
	},
	{
		"displayName": "Return All",
		"name": "returnAll",
		"type": "boolean",
		"default": false,
		"description": "Whether to return all results by paginating through every page, or only the first page. Each page consumes API credits.",
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.video.comments.replies.list"
				]
			}
		}
	},
	{
		"displayName": "URL",
		"name": "url",
		"type": "string",
		"default": "",
		"description": "Link to the YouTube video whose transcript should be returned.",
		"placeholder": "e.g. https://example.com/page",
		"required": true,
		"routing": {
			"send": {
				"type": "query",
				"property": "url"
			}
		},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.video.transcript.get"
				]
			}
		}
	},
	{
		"displayName": "Additional Fields",
		"name": "additionalOptions",
		"type": "collection",
		"placeholder": "Add Field",
		"default": {},
		"displayOptions": {
			"show": {
				"resource": [
					"youtube"
				],
				"operation": [
					"youtube.video.transcript.get"
				]
			}
		},
		"options": [
			{
				"displayName": "Language",
				"name": "language",
				"type": "string",
				"default": "",
				"description": "Optional ISO 639-1 language code (two letters) to prefer when multiple transcripts exist.",
				"routing": {
					"send": {
						"type": "query",
						"property": "language"
					}
				}
			}
		]
	}
];
